<?php
/*
Without error
Mandatory: formLabel
Optional: formHint (default: no span.form-hint outputted)
Optional: formLabelBold true|false (default: no wrapper span.form-label-bold outputted)
Optional: formType (default: text)
Optional: formSizeClass
*/

$formId = "id-{$formElement->getName()}";
$formName = $formElement->getName();

if(isset($formSet)){
    $formId = "{$formId}-{$formSet}";
    $formName = "{$formSet}[{$formName}]";
}

$hasErrors = !empty($formElement->getMessages());
$hasParentErrors = isset($hasParentErrors) && $hasParentErrors;

$formGroup = 'form-group';
$formGroup .= ($hasErrors && !$hasParentErrors) ? ' form-group-error' : '';
$formGroup .= (isset($additionalFormGroupClasses)) ? " {$additionalFormGroupClasses}" : '';

$formControlClasses = 'form-control'; 
$formControlClasses .= ($hasErrors) ? " form-control-error" : '';
$formControlClasses .= (isset($additionFormControlClass)) ? " {$additionFormControlClass}" : '';

?>

<div class="<?= $this->e($formGroup) ?>">
    <label class="form-label" for="<?= $formId ?>">

        <span class="question-text<?php if (isset($formLabelBold) && $formLabelBold): ?> form-label-bold<?php endif ?>">
            <?= $this->e($formLabel) ?>
        </span>

        <?php if (isset($formHint)): ?>
            <span class="form-hint"><?= $this->e($formHint) ?></span>
        <?php endif ?>

        <?php if (!$hasParentErrors): ?>
            <?php foreach($formElement->getMessages() as $message): ?>
                <span class="error-message"><?=$this->e($this->fieldError($formElement->getName(), $message))?></span>
            <?php endforeach ?>
        <?php endif ?>

    </label>
    <input class="<?= $this->e($formControlClasses) ?>" name="<?=$this->e( $formName )?>" type="<?= $this->e($formType) ?>" id="<?= $formId ?>" value="<?=$this->e( $formElement->getValue() )?>">
</div>
