<h2 class="<?= (isset($headingLarge) && $headingLarge)?' heading-large':'heading-medium' ?>">
    Refunds team
</h2>

<address>
    <p>
        Email: <a href="mailto:poarefunds@justice.gov.uk">poarefunds@justice.gov.uk</a><br>
        Telephone: 0300 456 0300 (option 6)<br>
        Textphone: 0115 934 2778<br>
        Monday, Tuesday, Thursday, Friday 9am to 5pm<br>
        Wednesday 10am to 5pm<br>
        <a href="https://www.gov.uk/call-charges">Find out about call charges</a>
    </p>
</address>