TRUNCATE TABLE public.claim CASCADE;
TRUNCATE TABLE public.doctrine_migration_versions CASCADE;
TRUNCATE TABLE public.duplicate_claims CASCADE;
TRUNCATE TABLE public.note CASCADE;
TRUNCATE TABLE public.payment CASCADE;
TRUNCATE TABLE public.poa CASCADE;
TRUNCATE TABLE public.report CASCADE;
TRUNCATE TABLE public.user CASCADE;
TRUNCATE TABLE public.verification CASCADE;
