\set DATABASE_NAME `echo ${OPG_REFUNDS_DB_APPLICATIONS_NAME}`
\set DATABASE_WRITE_USERNAME `echo ${OPG_REFUNDS_DB_APPLICATIONS_WRITE_USERNAME}`
\set DATABASE_WRITE_PASSWORD `echo ${OPG_REFUNDS_DB_APPLICATIONS_WRITE_PASSWORD}`
\set DATABASE_FULL_USERNAME `echo ${OPG_REFUNDS_DB_APPLICATIONS_FULL_USERNAME}`
\set DATABASE_FULL_PASSWORD `echo ${OPG_REFUNDS_DB_APPLICATIONS_FULL_PASSWORD}`
\set DATABASE_MIGRATION_USERNAME `echo ${OPG_REFUNDS_DB_APPLICATIONS_MIGRATION_USERNAME}`
\set DATABASE_MIGRATION_PASSWORD `echo ${OPG_REFUNDS_DB_APPLICATIONS_MIGRATION_PASSWORD}`

\set APPLICATION_TABLE_NAME 'application'

CREATE DATABASE :DATABASE_NAME;

\c :DATABASE_NAME

BEGIN;

REVOKE ALL ON ALL SEQUENCES IN SCHEMA public FROM public;
REVOKE ALL ON ALL TABLES IN SCHEMA public FROM public;
REVOKE ALL ON SCHEMA public FROM public;

CREATE TABLE IF NOT EXISTS :APPLICATION_TABLE_NAME (
	"id" bigint NOT NULL,
	"created" timestamp with time zone NOT NULL,
	"processed" boolean NOT NULL,
	"data" bytea NULL,
	PRIMARY KEY(id)
);

CREATE INDEX IF NOT EXISTS created_at ON :APPLICATION_TABLE_NAME USING btree (created);
CREATE INDEX IF NOT EXISTS to_process ON :APPLICATION_TABLE_NAME USING btree (processed,created);

CREATE USER :DATABASE_WRITE_USERNAME WITH  PASSWORD :'DATABASE_WRITE_PASSWORD';

GRANT CONNECT ON DATABASE :DATABASE_NAME TO :DATABASE_WRITE_USERNAME;
GRANT USAGE ON SCHEMA public TO :DATABASE_WRITE_USERNAME;
GRANT INSERT ON :APPLICATION_TABLE_NAME TO :DATABASE_WRITE_USERNAME;

CREATE USER :DATABASE_FULL_USERNAME WITH  PASSWORD :'DATABASE_FULL_PASSWORD';

GRANT CONNECT ON DATABASE :DATABASE_NAME TO :DATABASE_FULL_USERNAME;
GRANT USAGE ON SCHEMA public TO :DATABASE_FULL_USERNAME;
GRANT SELECT, INSERT, UPDATE, DELETE ON ALL TABLES IN SCHEMA public TO :DATABASE_FULL_USERNAME;
GRANT USAGE, SELECT ON ALL SEQUENCES IN SCHEMA public TO :DATABASE_FULL_USERNAME;

CREATE USER :DATABASE_MIGRATION_USERNAME WITH  PASSWORD :'DATABASE_MIGRATION_PASSWORD';
GRANT ALL PRIVILEGES ON DATABASE :DATABASE_NAME TO :DATABASE_MIGRATION_USERNAME;
GRANT ALL PRIVILEGES ON SCHEMA public TO :DATABASE_MIGRATION_USERNAME;
GRANT ALL PRIVILEGES ON ALL TABLES IN SCHEMA public TO :DATABASE_MIGRATION_USERNAME;
GRANT ALL PRIVILEGES ON ALL SEQUENCES IN SCHEMA public TO :DATABASE_MIGRATION_USERNAME;

COMMIT;
