<?php
$title = "Sorry, something went wrong";
$this->layout('layout::standard', [
    'title' => $title,
]);
?>
<p>To keep this service secure, we haven’t saved any information you entered.</p>

<p>You'll need to start again.</p>

<p>
    <a class="button" href="<?= $this->url('home') ?>">Start a refund claim</a>
</p>

<?php $this->start('body-end') ?>
    <script>
        GOVUK.analytics.trackEvent('Error-page', '500')
    </script>
<?php $this->stop() ?>