<?php

use Opg\Refunds\Caseworker\DataModel\Cases\Claim as ClaimModel;

/*
Without error
Mandatory: claim
*/

/**
 * @var \Opg\Refunds\Caseworker\DataModel\Cases\Claim $claim
 */

?>

<?php if (in_array(\Opg\Refunds\Caseworker\DataModel\Cases\User::ROLE_ADMIN, $identity->getRoles())) { ?>
    <h2 id="administrator-functions" class="heading-medium heading-refunds">Administrator</h2>
    <dl class="details">

        <?php if(!$claim->canChangeOutcome() && !$claim->canReassignClaim()) { ?>
            <div class="">
                <dd class="details-definition">
                    No available administrator functions
                </dd>
            </div>
        <?php } ?>

        <?php if($claim->canChangeOutcome()) { ?>

            <div class="">
                <dt class="details-term">Outcome</dt>
                <dd class="details-definition">
                    <a class="button button-secondary" href="<?= $this->generateUrl('claim.change.outcome', ['claimId' => $claim->getId()]) ?>">Change claim outcome</a>
                </dd>
            </div>

        <?php } ?>

        <?php if($claim->canReassignClaim()) { ?>

            <div class="">
                <dt class="details-term">Assignment</dt>
                <dd class="details-definition">
                    <a class="button button-secondary" href="<?= $this->generateUrl('claim.reassign', ['claimId' => $claim->getId()]) ?>">Reassign claim</a>
                </dd>
            </div>

        <?php } ?>

    </dl>
<?php } ?>

