<?php
/*
Without error
Mandatory: claim
*/

/**
 * @var \Opg\Refunds\Caseworker\DataModel\Cases\Claim $claim
 */
?>

<?php $this->insert('snippet::donor-details', ['claim'=> $claim, 'donor' => $claim->getApplication()->getDonor()]) ?>

<?php $this->insert('snippet::attorney-details', ['claim'=> $claim, 'attorney' => $claim->getApplication()->getAttorney()]) ?>

<?php $this->insert('snippet::verification-details', [
    'claim'      => $claim,
    'caseNumber' => $claim->getApplication()->getCaseNumber(),
    'postcodes'  => $claim->getApplication()->getPostcodes()
]) ?>

<?php $this->insert('snippet::contact-details', ['application' => $claim->getApplication()]) ?>
