<?php

use Opg\Refunds\Caseworker\DataModel\Cases\Claim as ClaimModel;

/*
Without error
Mandatory: claim
*/

/**
 * @var \Opg\Refunds\Caseworker\DataModel\Cases\Claim $claim
 */

?>

<?php if($claim->getStatus() === ClaimModel::STATUS_PENDING || !$claim->isReadOnly()) { ?>
    <h2 class="heading-medium heading-refunds">Claim ownership</h2>
    <dl class="details">

        <?php if($claim->getStatus() === ClaimModel::STATUS_PENDING) { ?>
            <a class="button button-secondary" href="<?= $this->generateUrl('claim.assign', ['claimId' => $claim->getId()]) ?>">Assign claim to myself</a>
        <?php } elseif (!$claim->isReadOnly()) { ?>
            <a class="button button-secondary" href="<?= $this->generateUrl('claim.unassign', ['claimId' => $claim->getId()]) ?>">Return claim to queue</a>
        <?php } ?>

    </dl>
<?php } ?>