<?php
/*
Without error
Mandatory: attorney
*/

/**
 * @var \Opg\Refunds\Caseworker\DataModel\Applications\Attorney $attorney
 */
?>

<h2 class="heading-medium heading-refunds">Attorney details</h2>
<dl class="details">
    <div class="">
        <dt class="details-term">Name:</dt>
        <dd class="detail-definition"><?= $this->getFormattedName($attorney->getCurrent()->getName()) ?></dd>
    </div>
    <div class="">
        <dt class="details-term">Date of birth:</dt>
        <dd class="detail-definition"><?= $this->getDateOfBirthString($attorney->getCurrent()->getDob()) ?></dd>
    </div>
    <?php if ($attorney->getPoa() !== null && $attorney->getPoa()->getName() !== null) { ?>
        <div class="">
            <dt class="details-term">Name on power attorney documents:</dt>
            <dd class="detail-definition"><?= $this->getFormattedName($attorney->getPoa()->getName()) ?></dd>
        </div>
    <?php } ?>
</dl>