<?php
/*
Without error
Mandatory: donor
*/

/**
 * @var \Opg\Refunds\Caseworker\DataModel\Cases\Claim $claim
 * @var \Opg\Refunds\Caseworker\DataModel\Applications\Donor $donor
 */
?>

<h2 class="heading-medium heading-refunds">
    Donor details<?= $claim->getApplication()->isDonorDeceased() ? ' (Deceased)' : '' ?>
</h2>

<dl class="details">
    <div class="">
        <dt class="details-term">Name</dt>
        <dd class="details-definition"><?= $this->e($donor->getCurrent()->getName()->getFormattedName()) ?></dd>
        <?php if (!$donor->hasPoaName() && $claim->hasPoas()) { ?>
            <dd class="details-verified">
                <i class="icon icon-tick" title="Verified">
                    <span class="visually-hidden">Verified</span>
                </i>
            </dd>
        <?php } ?>
    </div>
    <div class="">
        <dt class="details-term">Date of birth</dt>
        <dd class="details-definition"><?= $this->e($this->getDateOfBirthString($donor->getCurrent()->getDob())) ?></dd>
        <?php if ($claim->hasPoas()) { ?>
            <dd class="details-verified">
                <i class="icon icon-tick" title="Verified">
                    <span class="visually-hidden">Verified</span>
                </i>
            </dd>
        <?php } ?>
    </div>
    <?php if ($donor->hasPoaName()) { ?>
        <div class="">
            <dt class="details-term">Name on POA</dt>
            <dd class="details-definition"><?= $this->e($donor->getPoa()->getName()->getFormattedName()) ?></dd>
            <?php if ($claim->hasPoas()) { ?>
                <dd class="details-verified">
                    <i class="icon icon-tick" title="Verified">
                        <span class="visually-hidden">Verified</span>
                    </i>
                </dd>
            <?php } ?>
        </div>
    <?php } ?>
</dl>