<?php if(!empty($form->getMessages())) { ?>
    <div class="error-summary" role="group" aria-labelledby="error-heading" tabindex="-1">
        <h2 class="heading-medium error-summary-heading" id="error-heading">There is a problem</h2>
        <ul>
            <?php foreach ($form->getMessages() as $elementName=>$messages) { ?>
                <?php foreach ($messages as $message) { ?>
                    <li>
                        <?php if (empty($poaCaseNumbers)) { ?>
                            <a href="#id-<?= $this->e($elementName) ?>"><?=$this->e($this->summaryError($elementName, $message))?></a>
                        <?php } else { ?>
                            <a href="<?= $this->generateUrl('claim.search', [], ['orderBy' => 'received', 'sort' => 'desc', 'poaCaseNumbers' => $poaCaseNumbers]) ?>" target="_blank"><?=$this->e($this->summaryError($elementName, $message))?></a>
                        <?php } ?>
                    </li>
                <?php } ?>
            <?php } ?>
        </ul>
    </div>
<?php } ?>
