
<?php if( !empty($form->getMessages()) ){ ?>
    <div class="error-summary" role="alert" aria-labelledby="error-heading" tabindex="-1">
        <h1 class="heading-medium error-summary-heading" id="error-heading">There is a problem</h1>

        <ul class="error-summary-list">
            <?php foreach( $form->getMessages() as $elementName=>$messages ){ ?>
                <?php foreach( $messages as $message ){ ?>
                    <li><a href="#id-<?= $this->e($elementName) ?>"><?=$this->e($this->summaryError($elementName, $message))?></a></li>
                <?php } ?>
            <?php } ?>
        </ul>

    </div>
<?php } ?>
