<!-- Without error -->
<!-- Mandatory: formLabel -->
<!-- Optional: formHint (default: no span.form-hint outputted) -->
<!-- Optional: formLabelBold true|false (default: no wrapper span.form-label-bold outputted) -->
<!-- Optional: formType (default: text) -->

<div class="form-group">
    <label class="form-label" for="generic-id">
        <span class="form-label-bold"><?= $this->e($formLabel) ?></span>
        <span class="form-hint"><?= $this->e($formHint) ?></span>
    </label>
    <input class="form-control" name="name" type="<?= $this->e($formType) ?>" id="generic-id" value="<?=$this->e('xxx')?>">
</div>

<!-- With error (note form-group-error and form-control-error class names) -->
<div class="form-group form-group-error">
    <label class="form-label" for="generic-id">
        <span class="form-label-bold"><?= $this->e($formLabel) ?></span>
        <span class="form-hint"><?= $this->e($formHint) ?></span>
        <span class="error-message">Error message about full name goes here</span>
    </label>
    <input class="form-control form-control-error" name="name" type="<?= $this->e($formType) ?>" id="generic-id" value="<?=$this->e('xxx')?>">
</div>
