<?php

$elementId = "id-{$formElement->getName()}";

// Does the element have any validation errors
$hasErrors = !empty($formElement->getMessages());

// Can there be multiple values
$multiple = ( $formElement instanceof \Zend\Form\Element\MultiCheckbox );

// Currently checked values
$vales = $formElement->getValue() ?? array();

?>

<div class="form-group<?= ($hasErrors)?' form-group-error':'' ?>">

    <fieldset>

        <legend class="visually-hidden"><?= $this->e($question) ?></legend>

        <?php foreach($formElement->getMessages() as $message): ?>
            <p class="error-message"><?=$this->e($this->fieldError($formElement->getName(), $message))?></p>
        <?php endforeach ?>

        <?php foreach($options as $name => $option): ?>

            <div class="multiple-choice" <?php if (isset($option['dataTargetMarkup'])): ?>data-target="<?= "{$elementId}-{$name}-info" ?>"<?php endif ?>>

                <input id="<?= "{$elementId}-{$name}" ?>"
                       type="checkbox"
                       name="<?= $this->e($formElement->getName()) ?><?= ($multiple)?'[]':'' ?>"
                       value="<?= $this->e($formElement->getValueOptions()[$name]) ?>"<?= in_array($formElement->getValueOptions()[$name], $vales)?' checked':'' ?>>

                <label class="form-label" for="<?= "{$elementId}-{$name}" ?>">

                    <?php if (isset($option['optionLabelSuffix']) && $option['optionLabelSuffix']): ?><span class="bold-small"><?php endif ?>
                        <?= $option['optionLabel'] ?>
                        <?php if (isset($option['optionLabelSuffix']) && $option['optionLabelSuffix']): ?></span><?php endif ?>

                    <?php if (isset($option['optionLabelSuffix'])): ?>
                        <br>
                        <?= $option['optionLabelSuffix'] ?>
                    <?php endif ?>

                </label>

            </div>

            <?php if (isset($option['dataTargetMarkup']) && $option['dataTargetMarkup']): ?>
                <div class="panel panel-border-narrow js-hidden" id="<?= "{$elementId}-{$name}-info" ?>">
                    <?= $option['dataTargetMarkup'] ?>
                </div>
            <?php endif ?>

        <?php endforeach ?>

    </fieldset>

</div>