<?php

$elementId = "id-{$formElement->getName()}";

$hasErrors = !empty($formElement->getMessages());

$multiple = ( $formElement instanceof \Zend\Form\Element\MultiCheckbox );

?>

<div class="form-group<?= ($hasErrors)?' form-group-error':'' ?>">

    <fieldset>

        <legend class="visually-hidden"><?= $this->e($question) ?></legend>

        <?php foreach($formElement->getMessages() as $message): ?>
            <p class="error-message"><?= $this->e($message) ?></p>
        <?php endforeach ?>

        <?php foreach($options as $name => $option): ?>

            <div class="multiple-choice">

                <input id="<?= "{$elementId}-{$name}" ?>"
                       type="checkbox"
                       name="<?= $this->e($formElement->getName()) ?><?= ($multiple)?'[]':'' ?>"
                       value="<?= $this->e($formElement->getValueOptions()[$name]) ?>"<?= in_array($formElement->getValueOptions()[$name], $formElement->getValue())?' checked':'' ?>>

                <label class="form-label" for="<?= "{$elementId}-{$name}" ?>">

                    <?= $option['optionLabel'] ?>

                </label>

            </div>

        <?php endforeach ?>

    </fieldset>

</div>
