<?php

use Opg\Refunds\Caseworker\DataModel\Cases\Claim as ClaimModel;

/*
Without error
Mandatory: claim
*/

/**
 * @var \Opg\Refunds\Caseworker\DataModel\Cases\Claim $claim
 */

?>

<h2 class="heading-medium heading-refunds">Outcome</h2>

<?php if($claim->hasPoas() || $claim->isNoMerisPoas() || $claim->isNoSiriusPoas() || $claim->isClaimComplete()) { ?>
    <h2 class="notice notice-heading">
        <?php if ($claim->isClaimVerified()) { ?>
            <strong class="bold-small">Claim verified</strong>
            <i class="icon icon-tick" title="Verified">
                <span class="visually-hidden">Verified</span>
            </i>
        <?php } else { ?>
            <i class="icon icon-important">
                <span class="visually-hidden">Warning</span>
            </i>
            <strong class="bold-small">Claim unverified</strong>
        <?php } ?>
    </h2>
<?php } ?>

<dl class="details">

    <div class="">
        <dt class="details-term">Expected refund date</dt>
        <dd class="details-definition"><?= $this->e($this->getDayAndFullTextMonth($claim->getApplication()->getExpected())) ?></dd>
        <dd class="details-definition">
            <?php if ($claim->isClaimComplete() && !$claim->isReadOnly()) { ?>
                <p>
                    <?php if ($claim->isClaimVerified() && $claim->isClaimRefundNonZero()) { ?>
                        <a class="button" href="<?= $this->generateUrl('claim.approve', ['claimId' => $claim->getId()]) ?>">Approve claim</a>
                    <?php } ?>
                    <a class="button" href="<?= $this->generateUrl('claim.reject', ['claimId' => $claim->getId()]) ?>" style="background-color: red">Reject claim</a>
                </p>
            <?php } ?>
            <?php if ($claim->canResolveAsDuplicate()) { ?>
                <p>
                    <a class="button" href="<?= $this->generateUrl('claim.duplicate', ['claimId' => $claim->getId()]) ?>" style="background-color: red">Resolve as duplicate</a>
                </p>
            <?php } ?>
        </dd>
    </div>

    <?php if($claim->isClaimComplete() && $claim->isReadOnly()) { ?>
        
        <?php if ($claim->getStatus() === ClaimModel::STATUS_ACCEPTED) { ?>
            <div class="">
                <dt class="details-term">Claim approved</dt>
                <dd class="details-definition">
                    <span>Claim was approved on <?= $this->e($this->getFinishedDateString($claim->getFinishedDateTime())) ?></span>
                    <?php if ($claim->getPayment() !== null) { ?>
                        <br/><span>A payment of <?= $this->e($claim->getPayment()->getAmountString()) ?> was added to the spreadsheet on <?= $this->e($this->getFinishedDateString($claim->getPayment()->getAddedDateTime())) ?></span>
                    <?php } ?>
                </dd>
            </div>
        <?php } elseif ($claim->getStatus() === ClaimModel::STATUS_REJECTED) { ?>
            <div class="">
                <dt class="details-term">Claim rejected</dt>
                <dd class="details-definition">
                    Claim was rejected on <?= $this->e($this->getFinishedDateString($claim->getFinishedDateTime())) ?> due to '<?= $this->e($this->getRejectionReasonsText($claim->getRejectionReason())) ?>'<?= empty($claim->getRejectionReasonDescription()) ? '' : " with description '{$this->e($claim->getRejectionReasonDescription())}'" ?>
                </dd>
            </div>
        <?php } ?>

        <?php if ($claim->getStatus() === ClaimModel::STATUS_ACCEPTED || $claim->getStatus() === ClaimModel::STATUS_REJECTED) { ?>
            <div class="">
                <dt class="details-term">Notifications</dt>
                <dd class="details-definition">
                    <?php if (!$claim->isOutcomeEmailSent() && !$claim->isOutcomeEmailSent()) { ?>
                        <span>None sent</span>
                    <?php } ?>
                    <?php if ($claim->isOutcomeEmailSent()) { ?>
                        <span><?= $this->e($this->getOutcomeEmailDescription($claim)) ?><br/></span>
                    <?php } ?>
                    <?php if ($claim->isOutcomeEmailSent()) { ?>
                        <span><?= $this->e($this->getOutcomeTextDescription($claim)) ?></span>
                    <?php } ?>
                </dd>
            </div>
        <?php } ?>

    <?php } ?>

</dl>