<?php
/*
Without error
Mandatory: claim
*/

/**
 * @var \Opg\Refunds\Caseworker\DataModel\Cases\Claim $claim
 */
?>

<h2 id="payment-details" class="heading-medium heading-refunds">Payment details</h2>
<dl class="details">
    <?php if ($claim->hasAccountHash() && $claim->hasAccountHashCount()) { ?>
        <div class="<?= $this->shouldShowPaymentDetailsUsedCountWarning($claim->getAccountHashCount()) ? 'details-warning' : '' ?>">
            <dd class="details-definition">
                <?php if ($this->shouldShowPaymentDetailsUsedCountWarning($claim->getAccountHashCount())) { ?>
                    <p class="notice">
                        <i class="icon icon-important">
                            <span class="visually-hidden">Warning</span>
                        </i>
                        <strong class="bold-small"><?= $this->e($this->getPaymentDetailsUsedText($claim->getAccountHashCount())) ?></strong>
                    </p>
                    <a href="<?= $this->generateUrl('claim.search', [], $this->getSearchParameters(['accountHash' => $this->e($claim->getAccountHash())])) ?>">Search for claims that use these details</a>
                <?php } else { ?>
                    <?= $this->e($this->getPaymentDetailsUsedText($claim->getAccountHashCount())) ?>
                <?php } ?>
            </dd>
        </div>
    <?php } ?>
    <div class="">
        <dt class="details-term">Refund by</dt>
        <dd class="details-definition"><?= $claim->getApplication()->isRefundByCheque() ? 'Cheque' : 'Bank transfer' ?></dd>
    </div>
    <div class="">
        <dt class="details-term">Total refund</dt>
        <dd class="details-definition"><?= $this->e($claim->getRefundTotalAmountString()) ?></dd>
    </div>
</dl>