<?php
/*
Without error
Mandatory: form
Mandatory: claim
*/

/**
 * @var \App\Form\Poa $form
 * @var \Opg\Refunds\Caseworker\DataModel\Cases\Claim $claim
 */

$attorney = $claim->getApplication()->getAttorney();
$attorneyName = $attorney->getPoaName() !== null ? $this->getFormattedName($attorney->getPoaName()) : $this->getFormattedName($attorney->getName());
$postcodes = $claim->getApplication()->getPostcodes();
?>

<form method="post" class="form">

    <?php $this->insert('snippet::form-csrf', ['form' => $form]) ?>

    <div>
        <h3 class="heading-small">Add power of attorney details</h3>

        <?php $this->insert('snippet::input-text', [
            'formElement' => $form->get('caseNumber'),
            'formLabel' => 'Case number',
            'formType' => 'text',
            'formLabelBold' => false
        ]) ?>

        <h3 class="heading-small">Received date - TBC?</h3>

        <?php $this->insert('snippet::input-received-date', [
            'formLabel' => 'Received date',
            'formElement' => $form->get('receivedDate'),
        ]) ?>
    </div>

    <?php $this->insert('snippet::input-radio', [
        'formElement' => $form->get('originalPaymentAmount'),
        'question' => 'Original payment amount',
        'options' => [
            'orMore' => [
                'optionLabel' => '£110 or more'
            ],
            'lessThan' => [
                'optionLabel' => 'Less than £110'
            ],
            'noRefund' => [
                'optionLabel' => 'No refund amount'
            ],
        ],
    ])
    ?>

    <h3 class="heading-small">Check verification details</h3>

    <?php $this->insert('snippet::input-radio', [
        'formElement' => $form->get('attorney'),
        'question' => "Does {$attorneyName} and {$this->getDateOfBirthString($attorney->getDob())} match one attorney's details on the POA?",
        'options' => [
            'yes' => [
                'optionLabel' => 'Yes'
            ],
            'no' => [
                'optionLabel' => 'No'
            ],
        ],
    ])
    ?>

    <?php if ($postcodes->getDonorPostcode() !== null) {
        $this->insert('snippet::input-radio', [
            'formElement' => $form->get('donor-postcode'),
            'question' => "Does {$postcodes->getDonorPostcode()} match the donor's address on the POA?",
            'options' => [
                'yes' => [
                    'optionLabel' => 'Yes'
                ],
                'no' => [
                    'optionLabel' => 'No'
                ],
            ],
        ]);
    }
    ?>

    <?php if ($postcodes->getAttorneyPostcode() !== null) {
        $this->insert('snippet::input-radio', [
            'formElement' => $form->get('attorney-postcode'),
            'question' => "Does {$postcodes->getAttorneyPostcode()} match any of the attorney addresses on the POA?",
            'options' => [
                'yes' => [
                    'optionLabel' => 'Yes'
                ],
                'no' => [
                    'optionLabel' => 'No'
                ],
            ],
        ]);
    }
    ?>

    <div class="form-group">
        <input id='return-submit' type='submit' class="button" name='submit' value='Save and return to claim'>
        <input id='add-submit' type='submit' class="button" name='submit' value='Save and add another'>
    </div>

    <a href="/claim/<?= $claim->getId() ?>">Cancel</a>

</form>