<p>You don’t need to know exact dates to claim a refund. You'll also get 0.5% interest on your refund amount.</p> 

<table>
    <caption class="visually-hidden">Table of refund amounts depending on when a power of attorney fee was paid.</caption>
    <thead>
        <tr>
            <th scope="col">When you paid a fee</th>
            <th class="numeric" scope="col">Refund for each power of attorney</th>
        </tr>
    </thead>
    <tbody>
        <tr>
            <td>Apr to Sept 2013</td>
            <td class="numeric">£54</td>

        </tr>
        <tr>
            <td>Oct 2013 to Mar 2014</td>
            <td class="numeric">£34</td>
        </tr>
        <tr>
            <td>Apr 2014 to Mar 2015</td>
            <td class="numeric">£37</td>
        </tr>
        <tr>
            <td>Apr 2015 to Mar 2016</td>
            <td class="numeric">£38</td>
        </tr>
        <tr>
            <td>Apr 2016 to Mar 2017</td>
            <td class="numeric">£45</td>
        </tr>
    </tbody>
</table>

<p class="text-after-table">You'll get half the refund amount if you paid a reduced fee ('remission').</p>
