\set DATABASE_NAME `echo ${DB_NAME}`
\set DATABASE_USERNAME `echo ${DB_USERNAME}`
\set DATABASE_PASSWORD `echo ${DB_PASSWORD}`

\c :DATABASE_NAME

BEGIN;

ALTER USER :DATABASE_USERNAME WITH PASSWORD :'DATABASE_PASSWORD';

-- COMMIT;
