<?php 
    $this->layout('layout::standard', [
        'title' => 'Page not found',
    ]);
?>

<p>If you entered a web address please check it was correct.</p>

<p>
    <a class="button" href="<?= $this->url('home') ?>">Start a refund claim</a>
</p>

<?php $this->start('body-end') ?>
    <script>
        GOVUK.analytics.trackEvent('Error-page', '404', { transport: 'beacon' })
    </script>
<?php $this->stop() ?>