<?php
$title = 'Accessibility statement for Claim a power of attorney refund';
$this->layout('layout::standard', [
    'title' => $title,
]);
?>

    <p>This online service is run by the <a href="https://www.gov.uk/government/organisations/office-of-the-public-guardian">Office of the Public Guardian</a>. We want as many people as possible to be able to use this service. For example, that means you should be able to:</p>
    <ul class="list list-bullet">
        <li>change colours, contrast levels and fonts</li>
        <li>zoom in up to 300% without the text spilling off the screen</li>
        <li>navigate most of the website using just a keyboard</li>
        <li>navigate most of the website using speech recognition software</li>
        <li>listen to most of the website using a screen reader (including the most recent versions of JAWS, NVDA and VoiceOver)</li>
    </ul>
    <p>We’ve also made the website text as simple as possible to understand.</p>
    <h2 class="heading-medium">Get help</h2>
    <p><a href="https://mcmw.abilitynet.org.uk">AbilityNet</a> has guidance about how to:</p>
    <ul class="list list-bullet">
        <li><a href="https://mcmw.abilitynet.org.uk/impairment/making-your-mouse-easier-to-use">make your mouse easier to use</a></li>
        <li><a href="https://mcmw.abilitynet.org.uk/category/keyboard-shortcuts">use your keyboard instead of a mouse</a></li>
        <li><a href="https://mcmw.abilitynet.org.uk/impairment/talking-to-your-device">talk to your device</a></li>
        <li><a href="https://mcmw.abilitynet.org.uk/impairment/make-your-device-talk-to-you">make your device talk to you</a></li>
        <li><a href="https://mcmw.abilitynet.org.uk/impairment/making-text-larger">make text larger</a></li>
        <li><a href="https://mcmw.abilitynet.org.uk/impairment/changing-your-colours">change your colours</a></li>
        <li><a href="https://mcmw.abilitynet.org.uk/impairment/magnifying-the-screen">magnify the screen</a></li>
    </ul>
    <h2 class="heading-medium">How accessible this website is</h2>
    <p>We know some parts of this website are not fully accessible:</p>
    <ul class="list list-bullet">
        <li>you cannot modify the line height or spacing of text</li>
        <li>some of our online forms are difficult to navigate using just a keyboard</li>
        <li>you cannot skip to the main content when using a screen reader</li>
    </ul>
    <a id="claim"><h2 class="heading-medium">What to do if you cannot access parts of this service</h2></a>
    <p>If you need help to use this service, call the Refunds Helpline.</p>
    <?php $this->insert('snippet::refunds-helpline');?>
    <a id="reporting"><h2 class="heading-medium">Reporting accessibility problems with this service</h2></a>
    <p>We’re always looking to improve the accessibility of this service. If you find any problems not listed on this page or think we’re not meeting accessibility requirements, please contact us. </p>
    <h3 class="heading-small">Email</h4>
    <p><a href="mailto:customerservices@publicguardian.gov.uk" target="_blank">customerservices@<wbr>publicguardian.gov.uk</a></p>
    <h3 class="heading-small">Telephone</h3>
    <p>0300 456 0300</p>
    <p>Monday to Friday 9:30am to 5pm, except Wednesday.</p>
    <p>Wednesday 10am to 5pm</p>
    <p><a href="https://www.gov.uk/call-charges">Find out about call charges</a></p>
    <h3 class="heading-small">Textphone</h3>
    0115 934 2778</h4>
    <h2 class="heading-medium">Enforcement procedure</h2>
    <p>The Equality and Human Rights Commission (EHRC) is responsible for enforcing the Public Sector Bodies (Websites and Mobile Applications) (No. 2) Accessibility Regulations 2018 (the ‘accessibility regulations’). If you’re not happy with how we respond to your complaint, <a href="https://www.equalityadvisoryservice.com" target="_blank">contact the Equality Advisory and Support Service (EASS)</a>.</p>
    <h2 class="heading-medium">Technical information about this website’s accessibility</h2>
    <p>The Office of the Public Guardian is committed to making its online services accessible, in accordance with the Public Sector Bodies (Websites and Mobile Applications) (No. 2) Accessibility Regulations 2018.</p>
    <h3 class="heading-medium">Compliance status</h3>
    <p>This website is partially compliant with the <a href="https://www.w3.org/TR/WCAG21" target="_blank">Web Content Accessibility Guidelines version 2.1</a> AA standard, due to the non-compliances listed below.</p>
    <h2 class="heading-medium">Non-accessible content</h2>
    <p>This service was fully compliant with Web Content Accessibility Guidelines (WCAG) 2.0 when we tested the service on 18 October 2017.</p>
    <p>We carried out a <a href="https://www.gov.uk/government/publications/doing-a-basic-accessibility-check-if-you-cant-do-a-detailed-one">basic accessibility check</a> on the service on 23 September 2020 - this is a simplified version of the Web Content Accessibility Guidelines (WCAG) 2.1.</p>
    <p>We found one issue during this check.</p>
    <ul class="list list-bullet">
        <li>Users are not warned when their session will timeout and lose any data they’ve entered</li>
    </ul>
    <p>This service will end in February 2021.</p>
    <p>If you cannot use the service, we have an assisted digital team who will help you <a href="#claim">claim a power of attorney refund.</a></p>
    <p>If you find any accessibility issues we’ve not listed, you can tell us about them by contacting our <a href="#reporting">customer service team</a>. We’ll deal with any accessibility issues you find on a case by case basis</p>
    <h3 class="heading-medium">Disproportionate burden</h3>
    <p>Not applicable</p>
    <h3 class="heading-medium">Content that’s not within the scope of the accessibility regulations</h3>
    <p>Not applicable</p>
    <h2 class="heading-medium">Preparation of this accessibility statement</h2>
    <p>This statement was prepared on 21 Sep 2020.</p>
    <p>This service was last tested on 18 October 2017. The test was carried out by Digital Accessibility Centre (DAC).</p></font>
</div>
