<?php
$title = 'Privacy notice';
$this->layout('layout::standard', [
    'title' => $title,
]);
?>

<p>This privacy notice explains why the Office of the Public Guardian (OPG) collects personal data when you use the ‘Claim a power of attorney refund’ service.</p>

<p>This notice also explains how we store this data, what we do with it, how you can get a copy of the data we have about you, and how you can complain if you think we’ve done something wrong.</p>

<p>You should read this privacy notice alongside <a href="https://www.gov.uk/government/organisations/office-of-the-public-guardian/about/personal-information-charter" target="_blank">OPG’s personal information charter</a>, which sets out the standards you can expect when we ask for, use or share your personal information.</p>


<h2 class="heading-medium">Who manages the Claim a power of attorney refund service</h2>

<p>This service is managed by OPG, which is an executive agency sponsored by the Ministry of Justice (MoJ). </p>

<p>MoJ is the data controller for the personal data we store. <a href="https://www.gov.uk/government/organisations/office-of-the-public-guardian/about/personal-information-charter" target="_blank">OPG’s personal information charter</a> explains how we process personal data.</p>

<p>You can find more information about using the Claim a power of attorney refund service in our <a href="/terms">terms of use</a> and <a href="/cookies">cookies policy</a>.</p>


<h2 class="heading-medium">Why we collect personal data and how we use it</h2>

<p>In order to use this service, you need to enter personal information about the donor and one of their attorneys.</p>

<p>We use the information you provide to determine whether the donor is eligible for a refund, and if they are, to pay the refund.</p>


<h2 class="heading-medium">The personal data we collect</h2>

<p>We only collect personal data that we need to assess and process your refund claim. This includes:</p>

<ul class="list list-bullet">
    <li>the donor’s name, date of birth, address and bank account details</li>
    <li>an attorney’s name, date of birth and postcode</li>
    <li>the email address or mobile phone number of the person applying for the refund</li>
</ul>

<p>We might also collect information if you contact the Refunds team. For example, if you contact us to ask a question or to make a complaint.</p>

<p>The legal basis for processing this data is that your use of this service is optional.</p>

<p>Your use of this online service is optional. You can also claim a refund by phone.</p>

<h3 class="heading-small">Cookies and site usage data</h3>

<p>OPG collects site usage information from this service. This allows us to see how the service is being used so we can improve it. This information does not contain any personal data and is stored separately from the information you enter when using this service.</p>

<p>Find out more about <a href="/cookies">cookies and site usage data</a>.</p>


<h2 class="heading-medium">How we store data</h2>

<p>Information you enter online will be temporarily and securely held inline with our <a href="/cookies">cookie policy</a> so that you can progress through your claim. However, this information won't be stored unless, and until, you choose to submit your claim.</p>

<p>Once you submit your refund claim, the information you have entered  will be stored in a secure database within the European Economic Area (EEA). However, due to the global nature of the internet, the data sent to and from the database may transit through countries outside of the EEA. Data is not stored in a non-EEA country.</p>

<p>It may sometimes be necessary to transfer personal information overseas. Any transfers made will fully comply with all aspects of data protection law. For example, data is encrypted during transfer.</p>

<h3 class="heading-small">Who has access to data in the service</h3>

<p>Our hosting provider (Amazon Web Services) and MoJ staff responsible for supporting the service have access to the secure database.</p>

<p>OPG staff who are responsible for processing refund claims also have access to the data.</p>

<p>All staff who have access to the data have MoJ security clearance.</p>

<p><a href="https://www.gov.uk/government/organisations/office-of-the-public-guardian/about/personal-information-charter" target="_blank">OPG’s personal information charter</a>, which sets out the standards you can expect when we ask for or use your personal information.</p>

<h3 class="heading-small">Bank details</h3>

<p>The power of attorney refund service encrypts bank details. This means our staff can't see the bank account number or sort code you enter.</p>

<h3 class="heading-small">How long we keep data</h3>

<p>We will keep your personal data inline with the <a href="https://www.gov.uk/government/publications/record-retention-and-disposition-schedules" target="_blank">OPG’s retention policy</a>.</p>

<h3 class="heading-small">Change or delete information you’ve provided</h3>

<p>Contact the Refunds team if you want to change or delete any of the information you’ve submitted.</p>


<h2 class="heading-medium">Sharing personal data</h2>

<p>We will only share the information you give when the law says we can. For example, we may share information with the police to help them prevent or investigate crime. </p>

<p>We will never:</p>

<ul class="list list-bullet">
    <li>share your information with other organisations for marketing, market research or commercial purposes</li>
    <li>sell or rent your data to third parties</li>
</ul>

<p>We will share your data if we are required to do so by law, for example, by court order, or to prevent fraud or other crimes.</p>

<p>Neither Notify nor its SMS, email and post providers will use your personal information for direct marketing. <a href="https://www.notifications.service.gov.uk/features/security" target="_blank">Find out more about security and data protection on Notify</a>.</p>

<p>We encrypt the bank details you provide and securely transfer them to financial services provider Shared Services Connected Limited (SSCL). They only use these details to process refund payments in line with terms of service agreed between MoJ and SSCL.</p>


<h2 class="heading-medium">Access your personal information</h2>

<p>You can find out what personal data we we hold about you in the service by making a subject access request.</p>

<p><a href="https://www.gov.uk/government/organisations/office-of-the-public-guardian/about/personal-information-charter" target="_blank">Find out more about subject access requests</a>.</p>


<h2 class="heading-medium">Getting more information</h2>

<p>You can get more details on:</p>

<ul class="list list-bullet">
    <li>agreements we have with other organisations for sharing information</li>
    <li>when we can pass on personal information without telling you, for example, to help with the prevention or detection of crime or to produce anonymised statistics</li>
    <li>instructions we give to staff on how to collect, use or delete your personal data</li>
    <li>how we check that the information we hold is accurate and up-to- date</li>
    <li>how to make a complaint</li>
    <li>anything in this privacy notice</li>
    <li>what to do if you think that your personal data has been misused or mishandled</li>
</ul>

<p>For more information, please contact:</p>

<div class="panel panel-border">
    <p>
        MoJ Data Protection Officer<br/>
        Post point 10.38<br/>
        102 Petty France<br/>
        London<br/>
        SW1H 9AJ
    </p>
</div>


<h2 class="heading-medium">Changes to this notice</h2>

<p>We may change this privacy notice from time to time. When we do, we’ll update the ‘last updated’ date at the bottom of this page.</p>

<p>If these changes affect how your personal data is processed, OPG will take reasonable steps to let you know.</p>

<p>Any chances to this privacy notice will apply to you and your data immediately.</p>


<h2 class="heading-medium">Making a complaint</h2>

<p>When we ask for personal data, we will keep to the law. If you think that your information has not been handled correctly, in addition to contacting the MoJ Data Protection Officer, you can contact the Information Commissioner for independent advice about data protection at the address below:</p>

<div class="panel panel-border">
    <p>
        Information Commissioner's Office<br/>
        Wycliffe House<br/>
        Water Lane<br/>
        Wilmslow<br/>
        Cheshire<br/>
        SK9 5AF<br/><br/>
        Phone: 0303 123 1113<br/>
        Textphone: 01625 545860<br/>
        Monday to Friday, 9am to 4:30pm<br/><br/>
        <a href="http://www.ico.org.uk" target="_blank">www.ico.org.uk</a>
    </p>
</div>

<div class="meta-data group">
    <p class="modified-date">Last updated: March 2019</p>
</div>
