GRANT ALL PRIVILEGES ON DATABASE cases TO migration;
GRANT ALL PRIVILEGES ON SCHEMA public TO migration;
GRANT ALL PRIVILEGES ON ALL TABLES IN SCHEMA public TO migration;
GRANT ALL PRIVILEGES ON ALL SEQUENCES IN SCHEMA public TO migration;