SELECT COUNT(*) FROM public.claim;
SELECT COUNT(*) FROM public.doctrine_migration_versions;
SELECT COUNT(*) FROM public.duplicate_claims;
SELECT COUNT(*) FROM public.note;
SELECT COUNT(*) FROM public.payment;
SELECT COUNT(*) FROM public.poa;
SELECT COUNT(*) FROM public.report;
SELECT COUNT(*) FROM public.user;
SELECT COUNT(*) FROM public.verification;
