SELECT * FROM public.claim LIMIT 10;
SELECT * FROM public.doctrine_migration_versions LIMIT 10;
SELECT * FROM public.duplicate_claims LIMIT 10;
SELECT * FROM public.note LIMIT 10;
SELECT * FROM public.payment LIMIT 10;
SELECT * FROM public.poa LIMIT 10;
SELECT * FROM public.report LIMIT 10;
SELECT * FROM public.user LIMIT 10;
SELECT * FROM public.verification LIMIT 10;
