SELECT 'claim', COUNT(*) FROM public.claim;
SELECT 'doctrine_migration_versions', COUNT(*) FROM public.doctrine_migration_versions;
SELECT 'duplicate_claims', COUNT(*) FROM public.duplicate_claims;
SELECT 'note', COUNT(*) FROM public.note;
SELECT 'payment', COUNT(*) FROM public.payment;
SELECT 'poa', COUNT(*) FROM public.poa;
SELECT 'report', COUNT(*) FROM public.report;
SELECT 'user', COUNT(*) FROM public.user;
SELECT 'verification', COUNT(*) FROM public.verification;
