TRUNCATE TABLE public.claim;
TRUNCATE TABLE public.doctrine_migration_versions;
TRUNCATE TABLE public.duplicate_claims;
TRUNCATE TABLE public.note;
TRUNCATE TABLE public.payment;
TRUNCATE TABLE public.poa;
TRUNCATE TABLE public.report;
TRUNCATE TABLE public.user;
TRUNCATE TABLE public.verification;

DROP INDEX claim_pkey;
DROP INDEX doctrine_migration_versions_pkey;
DROP INDEX duplicate_claims_pkey;
DROP INDEX log_pkey;
DROP INDEX payment_pkey;
DROP INDEX poa_pkey;
DROP INDEX report_pkey;
DROP INDEX user_pkey;
DROP INDEX verification_pkey;
