\set DATABASE_FULL_PASSWORD `echo ${OPG_REFUNDS_DB_MIGRATION_PASSWORD}`

DROP USER IF EXISTS migration;
CREATE USER migration WITH PASSWORD :'DATABASE_FULL_PASSWORD';
GRANT ALL PRIVILEGES ON DATABASE :DATABASE_NAME TO migration;
GRANT ALL PRIVILEGES ON SCHEMA public TO migration;
GRANT ALL PRIVILEGES ON ALL TABLES IN SCHEMA public TO migration;
GRANT ALL PRIVILEGES ON ALL SEQUENCES IN SCHEMA public TO migration;
