\set DATABASE_FULL_PASSWORD `echo ${OPG_REFUNDS_DB_MIGRATION_PASSWORD}`

DROP USER IF EXISTS migration;
REVOKE ALL PRIVILEGES ON DATABASE cases TO migration;
REVOKE ALL PRIVILEGES ON SCHEMA public TO migration;

CREAT USER migration WITH PASSWORD :'DATABASE_FULL_PASSWORD';
GRANT ALL PRIVILEGES ON DATABASE cases TO migration;
GRANT ALL PRIVILEGES ON SCHEMA public TO migration;
