<!DOCTYPE html>
<html>

<head>
    <meta charset="utf-8">
    <title>
        GOV.UK elements
    </title>

    <!--[if gt IE 8]><!-->
    <link href="/assets/govuk_template/stylesheets/govuk-template.css" media="screen" rel="stylesheet">
    <!--<![endif]-->
    <!--[if IE 6]><link href="/assets/govuk_template/stylesheets/govuk-template-ie6.css" media="screen" rel="stylesheet" /><![endif]-->
    <!--[if IE 7]><link href="/assets/govuk_template/stylesheets/govuk-template-ie7.css" media="screen" rel="stylesheet" /><![endif]-->
    <!--[if IE 8]><link href="/assets/govuk_template/stylesheets/govuk-template-ie8.css" media="screen" rel="stylesheet" /><![endif]-->
    <link href="/assets/govuk_template/stylesheets/govuk-template-print.css" media="print" rel="stylesheet">

    <!--[if IE 8]><link href="/assets/govuk_template/stylesheets/fonts-ie8.css" media="all" rel="stylesheet" /><![endif]-->
    <!--[if gte IE 9]><!-->
    <link href="/assets/govuk_template/stylesheets/fonts.css" media="all" rel="stylesheet">
    <!--<![endif]-->
    <!--[if lt IE 9]><script src="/assets/govuk_template/javascripts/ie.js"></script><![endif]-->

    <link rel="shortcut icon" href="/assets/govuk_template/images/favicon.ico" type="image/x-icon">
    <link rel="mask-icon" href="/assets/govuk_template/images/gov.uk_logotype_crown.svg" color="#0b0c0c">
    <link rel="apple-touch-icon-precomposed" sizes="152x152" href="/assets/govuk_template/images/apple-touch-icon-152x152.png">
    <link rel="apple-touch-icon-precomposed" sizes="120x120" href="/assets/govuk_template/images/apple-touch-icon-120x120.png">

    <meta name="viewport" content="width=device-width, initial-scale=1">
    <meta property="og:image" content="/assets/govuk_template/images/opengraph-image.png">

    <!--[if gt IE 8]><!-->
    <link href="/assets/govuk_elements/stylesheets/main.css" rel="stylesheet" type="text/css">
    <!--<![endif]-->
    <!--[if IE 6]><link href="/assets/govuk_elements/stylesheets/main-ie6.css" rel="stylesheet" type="text/css" /><![endif]-->
    <!--[if IE 7]><link href="/assets/govuk_elements/stylesheets/main-ie7.css" rel="stylesheet" type="text/css" /><![endif]-->
    <!--[if IE 8]><link href="/assets/govuk_elements/stylesheets/main-ie8.css" rel="stylesheet" type="text/css" /><![endif]-->

    <link href="/assets/govuk_elements/stylesheets/vendor/prism.css" media="screen" rel="stylesheet">

    <link rel="stylesheet" type="text/css" href="/assets/style.css">

</head>

<body>

<header role="banner" id="global-header" class="with-proposition">
    <div class="header-wrapper">
        <div class="header-global">
            <div class="header-logo">
                <a href="https://www.gov.uk" title="Go to the GOV.UK homepage" id="logo" class="content">
                    <img src="/public/images/gov.uk_logotype_crown_invert_trans.png?0.19.2" width="36" height="32" alt=""> GOV.UK
                </a>
            </div>
        </div>

        <div class="header-proposition">
            <div class="content">
                <a href="#proposition-links" class="js-header-toggle menu">Menu</a>
                <nav id="proposition-menu">
                    <a href="/" id="proposition-name">OPG Walking Skeleton </a>
                </nav>
            </div>
        </div>

    </div>
</header>

<div id="global-header-bar"></div>

<main id="content" role="main">

    <?=$this->section('content')?>

</main>

<footer class="group js-footer" id="footer" role="contentinfo">
    <div class="footer-wrapper">
        <div class="footer-meta">
            <div class="footer-meta-inner">

                <ul>
                    <li>
                        <a href="/prototype-admin/clear-data">Clear data</a>
                    </li>
                </ul>

                <div class="open-government-licence">
                    <p class="logo"><a href="https://www.nationalarchives.gov.uk/doc/open-government-licence/version/3/" rel="license">Open Government Licence</a></p>

                    <p>All content is available under the <a href="https://www.nationalarchives.gov.uk/doc/open-government-licence/version/3/"
                                                             rel="license">Open Government Licence v3.0</a>, except where otherwise stated</p>

                </div>
            </div>

            <div class="copyright">
                <a href="https://www.nationalarchives.gov.uk/information-management/re-using-public-sector-information/copyright-and-re-use/crown-copyright/">© Crown copyright</a>
            </div>
        </div>
    </div>
</footer>

</body>

</html>
