<!DOCTYPE html>
<!--[if lt IE 9]><html class="lte-ie8" lang="en"><![endif]-->
<!--[if gt IE 8]><!--><html lang="en"><!--<![endif]-->

<head>
    <meta charset="utf-8" />
    <?php $subTitle = 'Power of attorney refunds'; ?>
    <title><?= (isset($title)) ? $this->e($title).' | ' : '' ?><?= ($title!=$subTitle) ? $subTitle.' | '  : '' ?>GOV.UK</title>

    <!--[if gt IE 8]><!--><link href="/assets/govuk_template/stylesheets/govuk-template.css" media="screen" rel="stylesheet" /><!--<![endif]-->
    <!--[if IE 6]><link href="/assets/govuk_template/stylesheets/govuk-template-ie6.css" media="screen" rel="stylesheet" /><![endif]-->
    <!--[if IE 7]><link href="/assets/govuk_template/stylesheets/govuk-template-ie7.css" media="screen" rel="stylesheet" /><![endif]-->
    <!--[if IE 8]><link href="/assets/govuk_template/stylesheets/govuk-template-ie8.css" media="screen" rel="stylesheet" /><![endif]-->
    <link href="/assets/govuk_template/stylesheets/govuk-template-print.css" media="print" rel="stylesheet" />

    <!--[if IE 8]><link href="/assets/govuk_template/stylesheets/fonts-ie8.css" media="all" rel="stylesheet" /><![endif]-->
    <!--[if gte IE 9]><!--><link href="/assets/govuk_template/stylesheets/fonts.css" media="all" rel="stylesheet" /><!--<![endif]-->
    <!--[if lt IE 9]><script src="/assets/govuk_template/javascripts/ie.js"></script><![endif]-->

    <link rel="shortcut icon" href="/assets/govuk_template/images/favicon.ico" type="image/x-icon" />

    <link rel="mask-icon" href="/assets/govuk_template/images/gov.uk_logotype_crown.svg" color="#0b0c0c">
    <link rel="apple-touch-icon" sizes="180x180" href="/assets/govuk_template/images/apple-touch-icon-180x180.png">
    <link rel="apple-touch-icon" sizes="167x167" href="/assets/govuk_template/images/apple-touch-icon-167x167.png">
    <link rel="apple-touch-icon" sizes="152x152" href="/assets/govuk_template/images/apple-touch-icon-152x152.png">
    <link rel="apple-touch-icon" href="/assets/govuk_template/images/apple-touch-icon.png">


    <meta name="theme-color" content="#0b0c0c" />

    <meta name="viewport" content="width=device-width, initial-scale=1">
    <meta property="og:image" content="/assets/govuk_template/images/opengraph-image.png">

    <!--[if gt IE 8]><!-->
    <link href="/assets/govuk-elements-styles.css" rel="stylesheet" type="text/css">
    <!--<![endif]-->
    <!--[if IE 6]><link href="/assets/govuk-elements-styles-ie6.css" rel="stylesheet" type="text/css" /><![endif]-->
    <!--[if IE 7]><link href="/assets/govuk-elements-styles-ie7.css" rel="stylesheet" type="text/css" /><![endif]-->
    <!--[if IE 8]><link href="/assets/govuk-elements-styles-ie8.css" rel="stylesheet" type="text/css" /><![endif]-->

</head>

<body>
    <script>document.body.className = ((document.body.className) ? document.body.className + ' js-enabled' : 'js-enabled');</script>

    <div id="skiplink-container">
      <div>
        <a href="#content" class="skiplink">Skip to main content</a>
      </div>
    </div>

    <div id="global-cookie-message">
      
        <p>GOV.UK uses cookies to make the site simpler. <a href="/cookies">Find out more about cookies</a></p>
      
    </div>

    <header role="banner" id="global-header" class="with-proposition">
        <div class="header-wrapper">
            <div class="header-global">
                <div class="header-logo">
                    <a href="https://www.gov.uk" title="Go to the GOV.UK homepage" id="logo" class="content">
                        <img src="/assets/govuk_template/images/gov.uk_logotype_crown_invert_trans.png" width="36" height="32" alt=""> GOV.UK
                    </a>
                </div>
            </div>

            <div class="header-proposition">
                <div class="content">
                    <nav id="proposition-menu">
                        <a href="/" id="proposition-name">Power of attorney refunds</a>
                    </nav>
                </div>
            </div>

        </div>
    </header>

    <div id="global-header-bar"></div>

    <main id="content" role="main">

    <div class="phase-banner">
        <p>
            <strong class="phase-tag">BETA</strong>
            <span>This is a new service – your <a href="#">feedback</a> will help us to improve it.</span>
        </p>
        </div>

        <?=$this->section('content')?>

    </main>

    <footer class="group js-footer" id="footer" role="contentinfo">

        <div class="footer-wrapper">

        <div class="footer-meta">
            <div class="footer-meta-inner">
            <h2 class="visuallyhidden">Support links</h2>
            <ul>
                <li><a href="/cookies">Cookies <span class="visuallyhidden">(Opens in a new window)</span></a></li>
                <li><a href="/terms">Terms and conditions <span class="visuallyhidden">(Opens in a new window)</span></a></li>
                <li>Built by <a href="https://www.gov.uk/government/organisations/office-of-the-public-guardian" rel="external" target="_blank">OPG Digital</a></li>
            </ul>

            <div class="open-government-licence">
                <p class="logo"><a href="https://www.nationalarchives.gov.uk/doc/open-government-licence/version/3/" rel="license">Open Government Licence</a></p>
                
                <p>All content is available under the <a href="https://www.nationalarchives.gov.uk/doc/open-government-licence/version/3/" rel="license">Open Government Licence v3.0</a>, except where otherwise stated</p>
                
            </div>
            </div>

            <div class="copyright">
            <a href="https://www.nationalarchives.gov.uk/information-management/re-using-public-sector-information/copyright-and-re-use/crown-copyright/">© Crown copyright</a>
            </div>
        </div>
        </div>
    </footer>

    <div id="global-app-error" class="app-error hidden"></div>
    <script src="/assets/govuk_template/javascripts/govuk-template.js"></script>

    <script src="/assets/main.js"></script>
    <script src="/assets/application.js"></script>

    <script>if (typeof window.GOVUK === 'undefined') document.body.className = document.body.className.replace('js-enabled', '');</script>

    </body>
</html>