<?php $this->layout('layout::default') ?>

<div class="grid-row">
  <div class="column-two-thirds">
    
    <h1 class="heading-xlarge">
        <?=$this->e($question)?>
    </h1>

    <?=$this->section('intro-text')?>

    <form class="form" action="donor-status" method="post">

        <div class="form-group">
          <fieldset>
            <legend class="visually-hidden"><?=$this->e($question)?></legend>
            <?=$this->section('content')?>
          </fieldset>
        </div>

        <div class="form-group">
          <input class="button" type="submit" value="Continue">
        </div>

      </form>

      <?=$this->section('help-text')?>
  </div>
</div>