<?php $this->layout('layout::default',[
    'title' => ($title) ?? null
]) ?>

<div class="grid-row">
    <div class="column-third">
        <?=$this->section('left-sidebar')?>
    </div>

    <div class="column-two-thirds">
        <?php if (isset($infoMessage)) { ?>
            <?= $infoMessage ?>
        <?php } ?>

        <?=$this->section('content')?>
    </div>
    <div class="column-third">
        <?=$this->section('right-sidebar')?>
    </div>
</div>