<?php $this->layout('layout::default',[
    'pageTitle' => ($pageTitle) ?? ($title) ?? null
]) ?>

<div class="grid-row">
  <div class="column-two-thirds">
    
    <?=$this->section('error-summary')?>

    <h1 class="heading-xlarge no-back-link">
        <?=$this->e( ($h1Title) ?? ($title) )?>
    </h1>

    <?=$this->section('content')?>
    
  </div>

  <div class="column-third">
    <?=$this->section('sidebar')?>
  </div>
</div>