<?php $this->layout('layout::default',[
    'title' => ($title) ?? null
])

/**
 * @var \Opg\Refunds\Caseworker\DataModel\Cases\Claim $claim
 */
?>

<h2 class="heading-large">
    <span><?= $claim->getReferenceNumber() ?> <?= $claim->getDonorName() ?></span>
    <?php if ($claim->isReadOnly()) { ?>
        <span class="heading-secondary"><?= $this->getStatusText($claim->getStatus()) ?> (Read Only)</span>
    <?php } ?>
</h2>

<div class="grid-row">
    <div class="column-one-fifth">
        <?=$this->section('left-sidebar')?>
    </div>
    <div class="column-three-fifths">
        <?=$this->section('content')?>
    </div>
    <div class="column-one-fifth">
        <?=$this->section('right-sidebar')?>
    </div>
</div>
