<?php $this->layout('layout::default',[
    'title' => ($title) ?? null
]) ?>

<h2 class="heading-large"><?= $claim->getReferenceNumber() ?> <?= $claim->getDonorName() ?></h2>

<div class="grid-row">
    <div class="column-one-fifth">
        <?=$this->section('left-sidebar')?>
    </div>
    <div class="column-three-fifths">
        <?=$this->section('content')?>
    </div>
    <div class="column-one-fifth">
        <?=$this->section('right-sidebar')?>
    </div>
</div>
