<?php
$title = 'Your bank details';
$title = ($applicant == 'donor') ? 'Your bank details' : 'Donor\'s bank details';
$this->layout('layout::standard',
    [
        'title' => $title
    ])
?>

<?php $this->insert('snippet::error-summary', [ 'form'=>$form ]) ?>

<p>
    If a refund is approved it will be paid to this account. Our terms and 
    conditions explain <a href="#">how we keep bank details safe</a>.
</p>

<p>We can only pay refunds to UK personal bank accounts.</p>

<form action="" method="post" class="form">

    <?php $this->insert('snippet::form-csrf', [ 'form'=>$form ]) ?>

    <?php $this->insert('snippet::input-text', [
        'formElement' => $form->get('name'),
        'formLabel' => 'Account holder name',
        'formType' => 'text',
        'formLabelBold' => true
    ]) ?>

    <?php $this->insert('snippet::input-text', [
        'formElement' => $form->get('account-number'),
        'formLabel' => 'Account number',
        'formHint' => '8-digit number on card',
        'formType' => 'text',
        'formLabelBold' => true,
        'additionFormControlClass' => 'form-control-1-4'
    ]) ?>

    <?php $this->insert('snippet::input-text', [
        'formElement' => $form->get('sort-code'),
        'formLabel' => 'Sort code',
        'formHint' => '6-digit number on card',
        'formType' => 'text',
        'formLabelBold' => true,
        'additionFormControlClass' => 'form-control-1-4'
    ]) ?>

    <div class="form-group">
        <input class="button" type="submit" value="Continue">
    </div>

</form>

