<?php $this->layout('layout::default', ['title' => 'Account set up expired']); ?>

<div class="grid-row">
    <div class="column-full">

        <h2 class="heading-medium heading-refunds">Account set up expired</h2>

        <p>Your account set up request has expired.</p>

        <p>Please contact a member of the Service Management Team and ask them to send you a new email so you can complete your account registration.</p>

        <p><a class="button" href="<?= $this->generateUrl('home') ?>">Continue</a></p>

    </div>
</div>
