<html>

<head>
    <meta charset="utf-8">
    <title>
        GOV.UK elements
    </title>

    <!--[if gt IE 8]><!-->
    <link href="https://govuk-elements.herokuapp.com/public/stylesheets/govuk-template.css?0.19.2" media="screen" rel="stylesheet">
    <!--<![endif]-->
    <!--[if IE 6]><link href="https://govuk-elements.herokuapp.com/public/stylesheets/govuk-template-ie6.css?0.19.2" media="screen" rel="stylesheet" /><![endif]-->
    <!--[if IE 7]><link href="https://govuk-elements.herokuapp.com/public/stylesheets/govuk-template-ie7.css?0.19.2" media="screen" rel="stylesheet" /><![endif]-->
    <!--[if IE 8]><link href="https://govuk-elements.herokuapp.com/public/stylesheets/govuk-template-ie8.css?0.19.2" media="screen" rel="stylesheet" /><![endif]-->
    <link href="https://govuk-elements.herokuapp.com/public/stylesheets/govuk-template-print.css?0.19.2" media="print" rel="stylesheet">

    <!--[if IE 8]><link href="https://govuk-elements.herokuapp.com/public/stylesheets/fonts-ie8.css?0.19.2" media="all" rel="stylesheet" /><![endif]-->
    <!--[if gte IE 9]><!-->
    <link href="https://govuk-elements.herokuapp.com/public/stylesheets/fonts.css?0.19.2" media="all" rel="stylesheet">
    <!--<![endif]-->
    <!--[if lt IE 9]><script src="https://govuk-elements.herokuapp.com/public/javascripts/ie.js?0.19.2"></script><![endif]-->

    <link rel="shortcut icon" href="https://govuk-elements.herokuapp.com/public/images/favicon.ico?0.19.2" type="image/x-icon">
    <link rel="mask-icon" href="https://govuk-elements.herokuapp.com/public/images/gov.uk_logotype_crown.svg?0.19.2" color="#0b0c0c">
    <link rel="apple-touch-icon-precomposed" sizes="152x152" href="https://govuk-elements.herokuapp.com/public/images/apple-touch-icon-152x152.png?0.19.2">
    <link rel="apple-touch-icon-precomposed" sizes="120x120" href="https://govuk-elements.herokuapp.com/public/images/apple-touch-icon-120x120.png?0.19.2">
    <link rel="apple-touch-icon-precomposed" sizes="76x76" href="https://govuk-elements.herokuapp.com/public/images/apple-touch-icon-76x76.png?0.19.2">
    <link rel="apple-touch-icon-precomposed" href="https://govuk-elements.herokuapp.com/public/images/apple-touch-icon-60x60.png?0.19.2">

    <meta name="viewport" content="width=device-width, initial-scale=1">
    <meta property="og:image" content="https://govuk-elements.herokuapp.com/public/images/opengraph-image.png?0.19.2">


    <!--[if gt IE 8]><!-->
    <link href="https://govuk-elements.herokuapp.com/public/stylesheets/govuk-elements-styles.css" rel="stylesheet" type="text/css">
    <!--<![endif]-->
    <!--[if IE 6]><link href="https://govuk-elements.herokuapp.com/public/stylesheets/govuk-elements-styles-ie6.css" rel="stylesheet" type="text/css" /><![endif]-->
    <!--[if IE 7]><link href="https://govuk-elements.herokuapp.com/public/stylesheets/govuk-elements-styles-ie7.css" rel="stylesheet" type="text/css" /><![endif]-->
    <!--[if IE 8]><link href="https://govuk-elements.herokuapp.com/public/stylesheets/govuk-elements-styles-ie8.css" rel="stylesheet" type="text/css" /><![endif]-->

    <!--[if gt IE 8]><!-->
    <link href="https://govuk-elements.herokuapp.com/public/stylesheets/elements-documentation.css" rel="stylesheet" type="text/css">
    <!--<![endif]-->
    <!--[if IE 6]><link href="https://govuk-elements.herokuapp.com/public/stylesheets/elements-documentation-ie6.css" rel="stylesheet" type="text/css" /><![endif]-->
    <!--[if IE 7]><link href="https://govuk-elements.herokuapp.com/public/stylesheets/elements-documentation-ie7.css" rel="stylesheet" type="text/css" /><![endif]-->
    <!--[if IE 8]><link href="https://govuk-elements.herokuapp.com/public/stylesheets/elements-documentation-ie8.css" rel="stylesheet" type="text/css" /><![endif]-->

    <link href="https://govuk-elements.herokuapp.com/public/stylesheets/vendor/prism.css" media="screen" rel="stylesheet">

</head>

<body>
<header role="banner" id="global-header" class="with-proposition">
    <div class="header-wrapper">
        <div class="header-global">
            <div class="header-logo">
                <a href="https://www.gov.uk" title="Go to the GOV.UK homepage" id="logo" class="content">
                    <img src="/public/images/gov.uk_logotype_crown_invert_trans.png?0.19.2" width="36" height="32" alt=""> GOV.UK
                </a>
            </div>
        </div>

        <div class="header-proposition">
            <div class="content">
                <a href="#proposition-links" class="js-header-toggle menu">Menu</a>
                <nav id="proposition-menu">
                    <a href="/" id="proposition-name">OPG Walking Skeleton </a>
                </nav>
            </div>
        </div>

    </div>
</header>

<div id="global-header-bar"></div>

<main id="content" role="main">
    <div class="grid-row">
        <div class="column-two-thirds">

            <h1 class="heading-xlarge">
                Account Details
            </h1>

            <?php if( !empty($form->getMessages()) ){ ?>
                <div class="error-summary" role="group" aria-labelledby="error-heading" tabindex="-1">
                    <h1 class="heading-medium error-summary-heading" id="error-heading">Error</h1>

                    <ul>
                        <?php foreach( $form->getMessages() as $message ){ ?>
                            <li><?=$this->e(array_pop($message))?></li>
                        <?php } ?>
                    </ul>

                </div>
            <?php } ?>

            <form action="" method="post" class="form">

                <!-- Date of birth -->
                <div class="form-group">
                    <fieldset>
                        <legend class="form-label-bold">Your account details</legend>

                        <div class="form-group">
                            <label class="form-label" for="name">Name</label>
                            <input class="form-control" name="name" type="text" id="name" value="<?=$this->e($form->getInputFilter()->getRawValue('name'))?>">
                        </div>

                        <div class="form-group">
                            <label class="form-label" for="sort-code">Sort Code</label>
                            <input class="form-control" name="sort-code" type="text" id="sort-code" value="<?=$this->e($form->getInputFilter()->getRawValue('sort-code'))?>">
                        </div>

                        <div class="form-group">
                            <label class="form-label" for="account-number">Account number</label>
                            <input class="form-control" name="account-number" type="text" id="account-number" value="<?=$this->e($form->getInputFilter()->getRawValue('account-number'))?>">
                        </div>

                    </fieldset>
                </div>

                <div class="form-group">
                    <input type="submit" class="button" value="Continue">
                </div>

            </form>

        </div>
    </div>
</main>

<footer class="group js-footer" id="footer" role="contentinfo">
    <div class="footer-wrapper">
        <div class="footer-meta">
            <div class="footer-meta-inner">

                <ul>
                    <li>
                        <a href="/prototype-admin/clear-data">Clear data</a>
                    </li>
                </ul>

                <div class="open-government-licence">
                    <p class="logo"><a href="https://www.nationalarchives.gov.uk/doc/open-government-licence/version/3/" rel="license">Open Government Licence</a></p>

                    <p>All content is available under the <a href="https://www.nationalarchives.gov.uk/doc/open-government-licence/version/3/"
                                                             rel="license">Open Government Licence v3.0</a>, except where otherwise stated</p>

                </div>
            </div>

            <div class="copyright">
                <a href="https://www.nationalarchives.gov.uk/information-management/re-using-public-sector-information/copyright-and-re-use/crown-copyright/">© Crown copyright</a>
            </div>
        </div>
    </div>
</footer>

</body>

</html>