<?php
$title = 'Your bank details';
$this->layout('layout::standard',
    [
        'title' => $title
    ])
?>

<?php $this->insert('snippet::error-summary', [ 'form'=>$form ]) ?>

<p>This must be a UK personal account.</p>

<p>If a refund is approved it will be paid to this account.</p>

<form action="" method="post" class="form">

    <?php $this->insert('snippet::form-csrf', [ 'form'=>$form ]) ?>

    <?php $this->insert('snippet::input-text', [
        'formElement' => $form->get('name'),
        'formLabel' => 'Account holder name',
        'formHint' => "As it appears on cards and statements",
        'formType' => 'text',
        'formLabelBold' => true
    ]) ?>

    <?php $this->insert('snippet::input-text', [
        'formElement' => $form->get('account-number'),
        'formLabel' => 'Account number',
        'formHint' => '8-digit number shown on bank cards and statements',
        'formType' => 'text',
        'formLabelBold' => true
    ]) ?>

    <?php $this->insert('snippet::input-text', [
        'formElement' => $form->get('sort-code'),
        'formLabel' => 'Sort code',
        'formHint' => '6-digit number shown on bank cards and statements',
        'formType' => 'text',
        'formLabelBold' => true
    ]) ?>

    <h2 class="heading-medium">Statement of truth</h2>

    <p>
        By submitting this claim you confirm that, to the best of your knowledge:
    </p>

    <ul class="list list-bullet">
        <li>you are entitled to claim a refund</li>
        <li>the details you have given are correct </li>
    </ul>

    <div class="form-group">
        <input type="submit" class="button" value="Confirm and submit claim">
    </div>

</form>

