<?php
$title = 'Your details (attorney)';
$this->layout('layout::standard', [
    'title' => $title,
]);
?>

<?php $this->insert('snippet::error-summary', [ 'form'=>$form ]) ?>

<form class="form" action="<?= $form->getAttribute('action') ?? $this->url() ?>" method="<?= $this->e(strtolower($form->getAttribute('method'))) ?>">

    <?php $this->insert('snippet::form-csrf', [ 'form'=>$form ]) ?>

    <fieldset>
        <legend class="form-label-bold">Your name</legend>

        <?php $this->insert('snippet::input-text', [
            'formElement' => $form->get('title'),
            'formLabel' => 'Title',
            'formType' => 'text',
            'formLabelBold' => false
        ]) ?>

        <?php $this->insert('snippet::input-text', [
            'formElement' => $form->get('first'),
            'formLabel' => 'First names',
            'formType' => 'text',
            'formLabelBold' => false
        ]) ?>

        <?php $this->insert('snippet::input-text', [
            'formElement' => $form->get('last'),
            'formLabel' => 'Last name',
            'formType' => 'text',
            'formLabelBold' => false
        ]) ?>

    </fieldset>

    <div class="form-group">
        <fieldset>
            <legend class="form-label-bold">
                Your date of birth
                <span class="form-hint">For example, 31 3 1980</span>
            </legend>

            <div class="form-date">
                <div class="form-group form-group-day">
                    <?php $this->insert('snippet::input-text', [
                        'formElement' => $form->get('day'),
                        'formLabel' => 'Day',
                        'formType' => 'number',
                        'formLabelBold' => false
                    ]) ?>
                </div>

                <div class="form-group form-group-month">
                    <?php $this->insert('snippet::input-text', [
                        'formElement' => $form->get('month'),
                        'formLabel' => 'Month',
                        'formType' => 'number',
                        'formLabelBold' => false
                    ]) ?>
                </div>

                <div class="form-group form-group-year">
                    <?php $this->insert('snippet::input-text', [
                        'formElement' => $form->get('year'),
                        'formLabel' => 'Year',
                        'formType' => 'number',
                        'formLabelBold' => false
                    ]) ?>
                </div>
            </div>
        </fieldset>
    </div>

    <div class="form-group">
        <input class="button" type="submit" value="Continue">
    </div>

</form>


