<?php
$title = ($applicant == 'attorney') ? 'Your details (attorney)' : 'Attorney details';
$this->layout('layout::standard', [
    'title' => $title,
    'pageTitle' => (!empty($form->getMessages())) ? "Error: {$title}" : null,
]);

// Error messages are in a snippet as shared between donor and attorney page
$this->fetch('snippet::actor-errors', [
    'firstPerson' => ($applicant != 'donor')
]);
?>

<?php $this->start('error-summary') ?>
    <?php $this->insert('snippet::error-summary', [ 'form'=>$form ]) ?>
<?php $this->stop() ?>

<?php if ($applicant == 'donor'): ?>
<p>Please give the details of one of your attorneys.</p>
<p>The attorneys are the people you appointed in your power of attorney to make decisions on your behalf.</p>
<?php endif ?>

<form class="form" action="<?= $form->getAttribute('action') ?? $this->url() ?>" method="<?= $this->e(strtolower($form->getAttribute('method'))) ?>">

    <?php $this->insert('snippet::form-csrf', [ 'form'=>$form ]) ?>

    <fieldset>
        <legend class="form-label-bold"><?= ($applicant == 'donor') ? "Attorney name" : "Name" ?></legend>

        <?php $this->insert('snippet::input-text', [
            'formElement' => $form->get('title'),
            'formLabel' => 'Title',
            'formType' => 'text',
            'formLabelBold' => false,
            'additionFormControlClass' => 'form-control-1-8'
        ]) ?>

        <?php $this->insert('snippet::input-text', [
            'formElement' => $form->get('first'),
            'formLabel' => 'First names',
            'formType' => 'text',
            'formLabelBold' => false
        ]) ?>

        <?php $this->insert('snippet::input-text', [
            'formElement' => $form->get('last'),
            'formLabel' => 'Last name',
            'formType' => 'text',
            'formLabelBold' => false
        ]) ?>

    </fieldset>

    <div class="form-group">
        <div class="multiple-choice" data-target="name-on-poa">
            <?php $element = $form->get('poa-name-different'); ?>
            <input
                id="name-on-poa-checkbox"
                name="<?= $element->getName(); ?>"
                type="checkbox"
                value="yes"
                <?= ($element->getValue()=='yes') ? ' checked="checked"' : '' ?>
            >
            <label for="name-on-poa-checkbox">
                <?= ($applicant == 'donor') ? "Their" : "My" ?> name is different on the power of attorney documents
            </label>
        </div>
    
        <div class="panel panel-border-narrow js-hidden" id="name-on-poa">
            <fieldset>
                <legend class="form-label-bold"><?= ($applicant == 'donor') ? "Attorney name" : "Name" ?> on power of attorney documents</legend>

                <?php $this->insert('snippet::input-text', [
                    'formElement' => $form->get('poa-title'),
                    'formLabel' => 'Title',
                    'formType' => 'text',
                    'formLabelBold' => false,
                    'additionFormControlClass' => 'form-control-1-8'
                ]) ?>

                <?php $this->insert('snippet::input-text', [
                    'formElement' => $form->get('poa-first'),
                    'formLabel' => 'First names',
                    'formType' => 'text',
                    'formLabelBold' => false
                ]) ?>

                <?php $this->insert('snippet::input-text', [
                    'formElement' => $form->get('poa-last'),
                    'formLabel' => 'Last name',
                    'formType' => 'text',
                    'formLabelBold' => false
                ]) ?>

            </fieldset>
        </div>
    </div>

    <?php $this->insert('snippet::input-dob', [
        'formLabel' => ($applicant == 'donor') ? 'Attorney date of birth' : 'Date of birth',
        'formElement' => $form->get('dob'),
    ]) ?>

    <div class="form-group">
        <input class="button" type="submit" value="Continue">
    </div>

</form>


