<?php
$title = "You've already submitted a claim";
$this->layout('layout::standard', [
    'title' => $title,
]);
?>

<p>The link we sent you to access this service has already been used to claim a refund.</p>

<p>Each link can only be used once at the moment.
This is because this is a <a href="https://www.gov.uk/help/beta">beta service</a>.</p>

<h2 class="heading-medium">What happens next</h2>

<p>We sent you a message (email or text) to confirm we have your claim.</p>

<p>The a refund is approved it will be paid within 12 weeks from the date you submitted your claim.</p>

<h2 class="heading-medium">If you need help</h2>

<p>If you didn't use the link or you need help with your claim contact the refunds helpline.</p>

<?php $this->insert('snippet::refunds-helpline');?>