<?php
$title = 'We are in beta';
$this->layout('layout::default', [
    'title' => $title,
]);

/*
 * Possible reasons:
 * - no-cookie
 * - link-used
 * - missing-data
 * - expired
 * - invalid-signature
 */
?>
<div class="grid-row">
    <div class="column-two-thirds">

        <h1 class="heading-xlarge">
            <?= $this->e($title) ?>
        </h1>

        <p>You cannot access this page because: <?= $this->e($reason) ?></p>

    </div>
</div>