<?php $this->layout('layout::default', ['title' => 'Home']) ?>
THIS IS EDIT!!!
<h1><?= $caseworker->getName() ?></h1>

<table>
    <tr>
        <th>Email</th>
        <td><?= $caseworker->getEmail() ?></td>
    </tr>
    <tr>
        <th>Status</th>
        <td><?= $caseworker->getStatus() ?></td>
    </tr>
    <tr>
        <th>Roles</th>
        <td><?= $caseworker->getRoles() ?></td>
    </tr>
</table>

<p><a href="/caseworker">Back to Caseworkers</a></p>
