<?php
$title = 'Can you give a reference number?';
$this->layout('layout::standard', [
    'title' => $title,
]);
?>

<?php $this->insert('snippet::error-summary', [ 'form'=>$form ]) ?>

<p>Power of attorney reference numbers are:</p>

<ul class="list list-bullet">
    <li>on the registered document or related letters</li>
    <li>7 or 12 numbers long (with or without dashes)</li>
    <li>often marked ‘OPG reference number’ or ‘Our ref’</li>
</ul>

<form class="form" action="<?= $form->getAttribute('action') ?? $this->url() ?>" method="<?= $this->e(strtolower($form->getAttribute('method'))) ?>">

    <?php $this->insert('snippet::form-csrf', [ 'form'=>$form ]) ?>

    <?php $this->insert('snippet::input-radio', [
        'formElement' => $form->get('have-poa-case-number'),
        'question' => $title,
        'options' => [
            'yes' => [
                'optionLabel' => "Yes, I have a reference number",
                'dataTarget' => 'attorney-info',
                'dataTargetMarkup' => $this->fetch('snippet::input-text', [
                    'formElement' => $form->get('poa-case-number'),
                    'formLabel' => 'Reference number',
                    'formType' => 'text',
                    'formHint' => 'You don\'t need to include any dashes',
                    'formLabelBold' => false
                ])
            ],
            'no' => [
                'optionLabel' => "No, I can’t give a reference number"
            ]
        ],
    ])
    ?>

    <div class="form-group">
        <input class="button" type="submit" value="Continue">
    </div>

</form>