<?php $this->layout('layout::three-column', ['title' => 'Claim', 'claim' => $claim]);

/**
 * @var \Opg\Refunds\Caseworker\DataModel\Cases\Claim $claim
 * @var \App\Form\AbstractForm $form
 */

$this->addErrorMap([
    'message' => [
        'required' => [
            'summary'   => 'Please enter a user log message',
            'field'     => 'Enter a user log message'
        ]
    ]
]);
?>

<?php $this->start('left-sidebar') ?>
<?php $this->insert('snippet::all-details', ['claim' => $claim]) ?>
<?php $this->stop() ?>

<?php $this->start('right-sidebar') ?>
<?php $this->insert('snippet::payment-details', ['claim' => $claim]) ?>
<?php $this->insert('snippet::accept-reject-buttons', ['claim' => $claim]) ?>
<?php $this->stop() ?>

<?php $this->insert('snippet::error-summary', [ 'form'=>$form ]) ?>

<div>
    <h2 class="heading-medium">Sirius power of attorneys</h2>

    <?php foreach ($this->getSiriusPoas($claim) as $poa) {
        /** @var \Opg\Refunds\Caseworker\DataModel\Cases\Poa $poa */?>
        <div style="border: 1px solid lightgrey; padding: 10px; margin: 10px">
            <ul>
                <li>Case number: <?= $this->getFormattedCaseNumber($poa) ?></li>
                <li>Received date: <?= $this->getReceivedDateString($poa->getReceivedDate()) ?></li>
                <li>Original paid amount: <?= $this->getOriginalPaymentAmountString($poa) ?></li>
                <li>Refund amount: £TBD</li>
                <li>Total amount: £TBD</li>
                <li>Verification matches: <?= $this->getFormattedVerificationMatches($poa) ?></li>
            </ul>
        </div>
    <?php } ?>

    <?php if ($claim->isNoSiriusPoas()) { ?>
        <a class="button" href="/claim/<?= $claim->getId() ?>/poa/sirius/cancel-none-found">Cancel and return to add Sirius POA</a>
    <?php } else { ?>
        <a class="button" href="/claim/<?= $claim->getId() ?>/poa/sirius">Add Sirius POA</a>
        <?php if (!$this->hasSiriusPoas($claim)) { ?>
            <a class="button" href="/claim/<?= $claim->getId() ?>/poa/sirius/none-found">No Sirius POAs found</a>
        <?php } ?>
    <?php } ?>
</div>

<div>
    <h2 class="heading-medium">Meris power of attorneys</h2>

    <?php if ($claim->isNoMerisPoas()) { ?>
        <a class="button" href="/claim/<?= $claim->getId() ?>/poa/meris/cancel-none-found">Cancel and return to add Meris POA</a>
    <?php } else { ?>
        <a class="button" href="/claim/<?= $claim->getId() ?>/poa/meris">Add Meris POA</a>
        <?php if (!$this->hasMerisPoas($claim)) { ?>
            <a class="button" href="/claim/<?= $claim->getId() ?>/poa/meris/none-found">No Meris POAs found</a>
        <?php } ?>
    <?php } ?>
</div>

<h2 class="heading-medium">User log</h2>

<form method="post" class="form">

    <?php $this->insert('snippet::form-csrf', ['form' => $form]) ?>

    <fieldset>

        <?php $this->insert('snippet::input-text', [
            'formElement' => $form->get('message'),
            'formLabel' => 'Add a user log',
            'formType' => 'textarea',
            'formLabelBold' => false
        ]) ?>

    </fieldset>

    <div class="form-group">
        <input type="submit" class="button" value="Submit log" />
    </div>

</form>

<?php foreach ($claim->getLogs() as $log) { ?>
    <?php /** @var \Opg\Refunds\Caseworker\DataModel\Cases\Log $log */ ?>
    <div>
        <h3 class="heading-small"><?= $this->getLogDateString($log->getCreatedDateTime()) ?> <?= $this->getLogTimeString($log->getCreatedDateTime()) ?></h3>
        <h4 class="heading-small"><?= $log->getTitle() ?></h4>
        <p><?= $log->getMessage() ?></p>
        <?php if ($log->getUserName() !== null) { ?>
            <p>by <?= $log->getUserName() ?></p>
        <?php } ?>
    </div>
<?php } ?>
