<?php $this->layout('layout::three-column', ['title' => 'Claim', 'claim' => $claim]);

/**
 * @var \Opg\Refunds\Caseworker\DataModel\Cases\Claim $claim
 * @var \App\Form\ClaimApprove $form
 */
?>

<?php $this->start('left-sidebar') ?>
<?php $this->insert('snippet::all-details', ['claim' => $claim]) ?>
<?php $this->stop() ?>

<?php $this->start('right-sidebar') ?>
<?php $this->insert('snippet::payment-details', ['claim' => $claim]) ?>
<?php $this->stop() ?>

<?php $this->insert('snippet::error-summary', [ 'form'=>$form ]) ?>

<h2 class="heading-medium">Update contact details</h2>

<form method="post" class="form">

    <?php $this->insert('snippet::input-hidden', ['formElement' => $form->get('secret')]) ?>

    <p>We need your email address or mobile phone number in order to process your claim.</p>

    <p>We won't send you marketing messages or share your contact details with anyone else.</p>

    <div class="form-group">
        <input type='submit' class="button" name='submit' value='Approve claim'>
        <a class="button button-link" href="<?= $this->generateUrl('claim', ['id' => $claim->getId()]) ?>">Cancel and return back to claim</a>
    </div>

    <?php $this->insert('snippet::input-text', [
        'formElement' => $form->get('email'),
        'formLabel' => 'Email address',
        'formType' => 'email',
        'formLabelBold' => true,
        'additionFormControlClass' => 'form-control-3-4'
    ]) ?>

    <?php $this->insert('snippet::input-text', [
        'formElement' => $form->get('phone'),
        'formLabel' => 'Mobile number',
        'formType' => 'tel',
        'formLabelBold' => true,
        'additionFormControlClass' => 'form-control-3-4'
    ]) ?>

    <p>We'll only contact you to update you about your claim. We'll confirm that we've received your claim and let you know when it's been approved or rejected.</p>

    <div class="form-group">
        <div class="multiple-choice">
            <?php $element = $form->get('receive-notifications'); ?>
            <input type="hidden" value="yes" name="<?= $element->getName(); ?>">
            <input
                    id="receive-notifications-checkbox"
                    name="<?= $element->getName(); ?>"
                    type="checkbox"
                    value="no"
                <?= ($element->getValue()=='no') ? ' checked="checked"' : '' ?>
            >
            <label for="receive-notifications-checkbox">I don’t want these updates</label>
        </div>
    </div>

    <div class="form-group">
        <input type="submit" class="button" value="Update contact details">
        <?php if (!(empty($ad))): ?>
            <input style="margin-left: 20px;" class="button button-secondary" type="submit" value="Add a postal address instead" name="address" >
        <?php endif ?>
        <a class="button button-link" href="<?= $this->generateUrl('claim', ['id' => $claim->getId()]) ?>">Cancel and return back to claim</a>
    </div>

</form>
