<?php $this->layout('layout::three-column', ['title' => 'Claim', 'claim' => $claim]);

/**
 * @var \Opg\Refunds\Caseworker\DataModel\Cases\Claim $claim
 * @var \App\Form\AbstractForm $form
 */

$this->addErrorMap([
    'message' => [
        'required' => [
            'summary'   => 'Please enter a user note',
            'field'     => 'Enter a user note'
        ]
    ]
]);
?>

<?php $this->start('left-sidebar') ?>
<?php $this->insert('snippet::all-details', ['claim' => $claim]) ?>
<?php $this->stop() ?>

<?php $this->start('right-sidebar') ?>
<?php $this->insert('snippet::payment-details', ['claim' => $claim]) ?>
<?php $this->insert('snippet::outcome', ['claim' => $claim]) ?>
<?php $this->insert('snippet::admin-functions', ['claim' => $claim]) ?>
<?php $this->stop() ?>

<?php $this->insert('snippet::error-summary', [ 'form'=>$form ]) ?>

<div>
    <?php $this->insert('snippet::flash-messages', ['messages' => $messages]) ?>

    <h2 class="heading-medium">Sirius power of attorneys</h2>

    <?php if ($claim->hasSiriusPoas()) { ?>
        <table class="poa-table">
            <thead>
            <tr>
                <th>Case reference</th>
                <th>Received date</th>
                <th>Refund amount</th>
                <th>Interest amount</th>
                <th>Verification matches</th>
            </tr>
            </thead>
            <tbody>
            <?php foreach ($claim->getSiriusPoas() as $poa) {
                /** @var \Opg\Refunds\Caseworker\DataModel\Cases\Poa $poa */?>
                <tr>
                    <?php if ($claim->isReadOnly()) { ?>
                        <td><?= $this->e($this->getFormattedCaseNumber($poa)) ?></td>
                    <?php } else { ?>
                        <td>
                            <a href="<?= $this->generateUrl('claim.poa', ['claimId' => $claim->getId(), 'system' => 'sirius', 'id' => $poa->getId()]) ?>"><?= $this->e($this->getFormattedCaseNumber($poa)) ?></a>
                            <?php if (!$poa->isComplete()) { ?>
                                <span>(incomplete)</span>
                            <?php } ?>
                        </td>
                    <?php } ?>
                    <td><?= $this->e($this->getReceivedDateString($poa->getReceivedDate())) ?></td>
                    <td><?= $this->e($poa->getRefundAmountString()) ?></td>
                    <td><?= $this->e($poa->getRefundInterestAmountString()) ?></td>
                    <td><?= $this->e($this->getFormattedVerificationMatches($poa)) ?></td>
                </tr>
            <?php } ?>
            </tbody>
        </table>
    <?php } ?>

    <?php if (!$claim->isReadOnly()) { ?>
        <form method="post" class="form" action="<?= $this->generateUrl('claim.poa.none.found', ['id' => $claim->getId(), 'system' => 'sirius']) ?>">
            <?php $this->insert('snippet::input-hidden', ['formElement' => $poaNoneFoundForm->get('secret')]) ?>
            <?php if ($claim->isNoSiriusPoas()) { ?>
                <input class="button" type="submit" value="Cancel and return to add Sirius POA">
            <?php } else { ?>
                <a class="button" href="<?= $this->generateUrl('claim.poa', ['claimId' => $claim->getId(), 'system' => 'sirius']) ?>">Add Sirius POA</a>
                <?php if (!$claim->hasSiriusPoas()) { ?>
                    <input class="button-secondary" type="submit" value="No eligible Sirius POAs found">
                <?php } ?>
            <?php } ?>
        </form>
    <?php } ?>
</div>

<div>
    <h2 class="heading-medium">Meris power of attorneys</h2>

    <?php if ($claim->hasMerisPoas()) { ?>
        <table class="poa-table">
            <thead>
            <tr>
                <th>Case reference</th>
                <th>Received date</th>
                <th>Refund amount</th>
                <th>Interest amount</th>
                <th>Verification matches</th>
            </tr>
            </thead>
            <tbody>
            <?php foreach ($claim->getMerisPoas() as $poa) {
                /** @var \Opg\Refunds\Caseworker\DataModel\Cases\Poa $poa */?>
                <tr>
                    <?php if ($claim->isReadOnly()) { ?>
                        <td><?= $this->e($this->getFormattedCaseNumber($poa)) ?></td>
                    <?php } else { ?>
                        <td>
                            <a href="<?= $this->generateUrl('claim.poa', ['claimId' => $claim->getId(), 'system' => 'meris', 'id' => $poa->getId()]) ?>"><?= $this->e($this->getFormattedCaseNumber($poa)) ?></a>
                            <?php if (!$poa->isComplete()) { ?>
                                <span>(incomplete)</span>
                            <?php } ?>
                        </td>
                    <?php } ?>
                    <td><?= $this->e($this->getReceivedDateString($poa->getReceivedDate())) ?></td>
                    <td><?= $this->e($poa->getRefundAmountString()) ?></td>
                    <td><?= $this->e($poa->getRefundInterestAmountString()) ?></td>
                    <td><?= $this->e($this->getFormattedVerificationMatches($poa)) ?></td>
                </tr>
            <?php } ?>
            </tbody>
        </table>
    <?php } ?>

    <?php if (!$claim->isReadOnly()) { ?>
        <form method="post" class="form" action="<?= $this->generateUrl('claim.poa.none.found', ['id' => $claim->getId(), 'system' => 'meris']) ?>">
            <?php $this->insert('snippet::input-hidden', ['formElement' => $poaNoneFoundForm->get('secret')]) ?>
            <?php if ($claim->isNoMerisPoas()) { ?>
                <input class="button" type="submit" value="Cancel and return to add Meris POA">
            <?php } else { ?>
                <a class="button" href="<?= $this->generateUrl('claim.poa', ['claimId' => $claim->getId(), 'system' => 'meris']) ?>">Add Meris POA</a>
                <?php if (!$claim->hasMerisPoas()) { ?>
                    <input class="button-secondary" type="submit" value="No eligible Meris POAs found">
                <?php } ?>
            <?php } ?>
        </form>
    <?php } ?>
</div>

<h2 class="heading-medium heading-refunds">User note</h2>

<details>
    <summary>Add a user note</summary>
    <form method="post" class="form">

        <?php $this->insert('snippet::input-hidden', ['formElement' => $form->get('secret')]) ?>

        <?php $this->insert('snippet::input-text', [
            'formElement' => $form->get('message'),
            'formLabel' => 'message',
            'formType' => 'textarea',
            'formLabelBold' => false,
            'additionFormControlClass' => 'form-control-3-4'
        ]) ?>

        <input class="button button-secondary" type="submit" value="Submit note">
    </form>
</details>

<h2 class="heading-medium heading-refunds">Timeline</h2>

<div class="timeline">
    <ul>
        <?php foreach ($claim->getNotes() as $note) { ?>
            <?php /** @var \Opg\Refunds\Caseworker\DataModel\Cases\Note $note */ ?>
            <li>
                <p class="timeline-reference"><?= $this->e($this->getNoteDateString($note->getCreatedDateTime())) ?> <span class="time"><?= $this->e($this->getNoteTimeString($note->getCreatedDateTime())) ?></span></p>
                <h2><?= $this->e($this->getTypeTitleText($note->getType())) ?></h2>
                <p><?= nl2br($this->e($note->getMessage())) ?></p>
                <?php if ($note->getUserName() !== null) { ?>
                    <p>by <?= $this->e($note->getUserName()) ?></p>
                <?php } ?>
            </li>
        <?php } ?>
    </ul>
</div>
