<?php $this->layout('layout::default', ['title' => 'Search claims']) ?>
<?php
/**
 * @var \Opg\Refunds\Caseworker\DataModel\Cases\ClaimSummaryPage $claimSummaryPage
 */
?>

<div class="grid-row">
    <div class="column-full">

        <h2 class="heading-medium heading-refunds">
            Search claims

            <?php if(count($_GET) > 0) { ?>
                <a href="<?= $this->generateUrl('claim.search') ?>">Clear search</a>
            <?php } ?>
        </h2>

        <?php if (count($claimSummaryPage->getClaimSummaries()) > 0) { ?>

            <table>
                <thead>
                <tr>
                    <th>Claim code</th>
                    <th>Donor name</th>
                    <th>Received</th>
                    <th>Modified</th>
                    <th>Assigned To</th>
                    <th>Status</th>
                </tr>
                </thead>
                <tbody>

                <?php foreach ($claimSummaryPage->getClaimSummaries() as $claimSummary) { ?>
                    <?php /** @var \Opg\Refunds\Caseworker\DataModel\Cases\ClaimSummary $claimSummary */ ?>
                    <tr>
                        <td><a href="<?= $this->generateUrl('claim', ['id' => $claimSummary->getId()]) ?>"><?= $claimSummary->getReferenceNumber() ?></a></td>
                        <td><a href="<?= $this->generateUrl('claim.search', [], ['donorName' => $claimSummary->getDonorName()]) ?>"><?= $claimSummary->getDonorName() ?></td></a>
                        <td><?= $this->getDayAndFullTextMonth($claimSummary->getReceivedDateTime()) ?></td>
                        <td><?= $this->getTimeIntervalAgo($claimSummary->getUpdatedDateTime()) ?></td>
                        <td><a href="<?= $this->generateUrl('claim.search', [], ['assignedToId' => $claimSummary->getAssignedToId()]) ?>"><?= $claimSummary->getAssignedToName() ?></td></a>
                        <td><a href="<?= $this->generateUrl('claim.search', [], ['status' => $claimSummary->getStatus()]) ?>"><?= $claimSummary->getStatus() ?></td></a>
                    </tr>
                <?php } ?>

                </tbody>
            </table>

        <?php } else { ?>
            <table>
                <tr>
                    <td colspan="6">No claims found</td>
                </tr>
            </table>
        <?php } ?>

        <?php if ($claimSummaryPage->getPageCount() > 1) { ?>
            <div class="grid-row">
                <div class="column-one-fifth">
                    <p>
                        <?php if ($claimSummaryPage->getPage() > 1) { ?>
                            <a href="<?= $this->generateUrl('claim.search', [], array_merge($_GET, ['page' => $claimSummaryPage->getPage()-1])) ?>">Previous page</a>
                        <?php } ?>
                    </p>
                </div>
                <div class="column-three-fifths">
                    <p style="text-align: center">Page <?= $claimSummaryPage->getPage() ?> of <?= $claimSummaryPage->getPageCount() ?></p>
                </div>
                <div class="column-one-fifth">
                    <p style="text-align: right">
                        <?php if ($claimSummaryPage->getPage() < $claimSummaryPage->getPageCount()) { ?>
                            <a href="<?= $this->generateUrl('claim.search', [], array_merge($_GET, ['page' => $claimSummaryPage->getPage()+1])) ?>">Next page</a>
                        <?php } ?>
                    </p>
                </div>
            </div>
        <?php } ?>

    </div>
</div>
