<?php 
    $title = 'Your contact details';
    $this->layout('layout::standard',
    [
        'title' => $title
    ])
?>

<?php if( !empty($form->getMessages()) ){ ?>
    <div class="error-summary" role="group" aria-labelledby="error-heading" tabindex="-1">
        <h1 class="heading-medium error-summary-heading" id="error-heading">Error</h1>

        <ul>
            <?php foreach( $form->getMessages() as $message ){ ?>
                <li><a href="#id-email"><?=$this->e(array_pop($message))?></a></li>
            <?php } ?>
        </ul>

    </div>
<?php } ?>

<form action="" method="post" class="form">
    
    <div class="form-group">
        <fieldset>
            <legend class="visually-hidden"><?=$this->e($title)?></legend>

            <?php $this->insert('snippet::input-text', [
                'formElement' => $form->get('email'),
                'formLabel' => 'Email address',
                'formHint' => 'Enter your email address',
                'formType' => 'text',
                'formLabelBold' => true
            ]) ?>

            <?php $this->insert('snippet::input-text', [
                'formElement' => $form->get('mobile'),
                'formLabel' => 'Mobile number',
                'formHint' => 'A UK mobile number',
                'formType' => 'text',
                'formLabelBold' => true
            ]) ?>

        </fieldset>
    </div>

    <div class="form-group">
        <input type="submit" class="button" value="Continue">
    </div>

</form>

<?php $this->insert('snippet::help-text', [
        'title' => 'Testing',
        'markup' => '
            <p>Hello</p>
        '
]);