<?php
$title = 'Contact us';
$this->layout('layout::standard', [
    'title' => $title,
]);
?>

<p>Contact the Refunds Helpline if you have a question or need help to make a claim.</p>

<?php $this->insert('snippet::refunds-helpline');?>

<p>You can also write to us at:</p>

<p>
Power of attorney refunds service<br>
PO Box 16185<br>
Birmingham<br>
B2 2WH
</p>

<div class="panel panel-border-wide">
    <p>If you have any power of attorney reference numbers please include them in your letter.</p>
</div>