<?php 
$title = 'Your contact details';
$this->layout('layout::standard',
[
    'title' => $title,
    'pageTitle' => (!empty($form->getMessages())) ? "Error: {$title}" : null,
]);

$this->addErrorMap([
    'one-field-required' => [
        'required' => [
            'summary'   => 'You must choose a way to be contacted',
            'field'     => 'Choose how we contact you'
        ]
    ],
    'email' => [
        'required' => [
            'summary'   => 'You haven\'t given your email address',
            'field'     => 'Enter your email address'
        ],
        'email-invalid' => [
            'summary'   => 'Check your email address',
            'field'     => 'Enter a valid email address'
        ],
        // If the hostname was invalid, so was the email address.
        // Thus there's no need to output the hostname validation
        'hostname-invalid' => [
            'summary'   => '',
            'field'     => ''
        ],
    ],
    'phone' => [
        'required' => [
            'summary'   => 'You haven\'t given your phone number',
            'field'     => 'Enter your mobile number'
        ],
        'phone-invalid' => [
            'summary'   => 'Check your phone number',
            'field'     => 'Enter a valid mobile number'
        ]
    ],
    'address' => [
        'required' => [
            'summary'   => 'You haven\'t entered a postal address',
            'field'     => 'Enter the postal address'
        ],
        'too-long' => [
            'summary'   => 'Postal address is too long',
            'field'     => 'Enter a valid postal address'
        ],
    ],
]);
?>

<?php $this->start('error-summary') ?>
    <?php $this->insert('snippet::error-summary', [ 'form'=>$form ]) ?>
    <?php $this->insert('snippet::error-summary', [ 'form'=>$adForm ]) ?>
<?php $this->stop() ?>

<p>We need your email address or mobile phone number in order to process your claim.</p>

<form action="" method="post" class="form">

    <?php $this->insert('snippet::form-csrf', [ 'form'=>$form ]) ?>

    <?php $this->insert('snippet::input-text', [
        'formElement' => $form->get('email'),
        'formLabel' => 'Email address',
        'formType' => 'email',
        'formLabelBold' => true,
        'additionFormControlClass' => 'form-control-3-4'
    ]) ?>

    <?php $this->insert('snippet::input-text', [
        'formElement' => $form->get('phone'),
        'formLabel' => 'Mobile number',
        'formType' => 'tel',
        'formLabelBold' => true,
        'additionFormControlClass' => 'form-control-3-4'
    ]) ?>


    <p>We'll only contact you to confirm that we've received your claim and to let you know if your claim has been approved or rejected.</p>

    <p>We won't send you marketing messages or share your contact details with anyone else.</p>

    <div class="form-group">
        <div class="multiple-choice" data-target="notification-warning">
            <?php $element = $form->get('receive-notifications'); ?>
            <input type="hidden" value="yes" name="<?= $element->getName(); ?>">
            <input
                id="receive-notifications-checkbox"
                name="<?= $element->getName(); ?>"
                type="checkbox"
                value="no"
                <?= ($element->getValue()=='no') ? ' checked="checked"' : '' ?>
            >
            <label for="receive-notifications-checkbox">I don’t want updates</label>
        </div>

        <div class="panel panel-border-narrow js-hidden" id="notification-warning">
            <p>We won't be able to confirm that we've received your claim or let you know if your claim has been approved or rejected.</p>
        </div>
    </div>

    <div class="form-group">
        <input type="submit" class="button" value="Continue">
    </div>

</form>

<?php if (!(empty($ad) && !is_null($adForm))): ?>

    <h2 class="heading-medium">Can't supply email or phone number?</h2>

    <form action="" method="post" class="form">

        <?php $this->insert('snippet::form-csrf', [ 'form'=>$adForm ]) ?>

        <?php
            $this->insert('snippet::input-textarea', [
                'formElement' => $adForm->get('address'),
                'formLabel' => 'Postal address',
                'formType' => 'text',
                'formLabelBold' => false,
                'additionFormControlClass' => 'form-control-3-4'
            ]);
        ?>

        <div class="form-group">
            <input type="submit" class="button" value="Continue">
        </div>

    </form>
<?php endif ?>

