<?php 
$title = 'Their contact Address';
$this->layout('layout::standard',
[
    'title' => $title,
    'pageTitle' => (!empty($form->getMessages())) ? "Error: {$title}" : null,
]);

$this->addErrorMap([
    'address' => [
        'required' => [
            'summary'   => 'You haven\'t entered a postal address',
            'field'     => 'Enter the postal address'
        ],
        'too-long' => [
            'summary'   => 'Postal address is too long',
            'field'     => 'Enter a valid postal address'
        ],
    ],
]);
?>

<?php $this->start('error-summary') ?>
    <?php $this->insert('snippet::error-summary', [ 'form'=>$form ]) ?>
<?php $this->stop() ?>

<form action="" method="post" class="form">

    <?php $this->insert('snippet::form-csrf', [ 'form'=>$form ]) ?>

    <?php
    $this->insert('snippet::input-textarea', [
        'formElement' => $form->get('address'),
        'formLabel' => 'Postal address',
        'formType' => 'text',
        'formLabelBold' => false,
        'additionFormControlClass' => 'form-control-3-4'
    ]);
    ?>

    <div class="form-group">
        <div class="multiple-choice" data-target="notification-warning-ad">
            <?php $element = $form->get('receive-notifications'); ?>
            <input type="hidden" value="yes" name="<?= $element->getName(); ?>">
            <input
                    id="receive-notifications-checkbox-ad"
                    name="<?= $element->getName(); ?>"
                    type="checkbox"
                    value="no"
                <?= ($element->getValue()=='no') ? ' checked="checked"' : '' ?>
            >
            <label for="receive-notifications-checkbox-ad">They don’t want updates</label>
        </div>

        <div class="panel panel-border-narrow js-hidden" id="notification-warning-ad">
            <p>We won't be able to confirm that we've received their claim or let you know if your claim has been approved or rejected.</p>
        </div>
    </div>

    <div class="form-group">
        <input type="submit" class="button" value="Continue">
    </div>

</form>