<?php
$title = 'Cookies disabled';
$this->layout('layout::standard', [
    'title' => $title,
]);

?>

<p>To access the power of attorney refund service you'll need to 
    <a href="http://www.aboutcookies.org/default.aspx?page=1:" target="_blank">enable cookies on your device (opens new window)</a>.</p>

<p>You'll then be able to <a href="/">start a refund claim</a>.</p>

<p>If you can't enable cookies you can call the Refunds Helpline for help.</p>

<?php $this->insert('snippet::refunds-helpline');?>