<?php
$title = 'Cookies disabled ';
$this->layout('layout::default', [
    'title' => $title,
]);

?>
<div class="grid-row">
    <div class="column-two-thirds">

        <h1 class="heading-xlarge">
            <?= $this->e($title) ?>
        </h1>

        <p>You can't currently access the Claim a power of attorney refund service because your cookies have been disabled.</p>

        <p><a href="http://www.aboutcookies.org/default.aspx?page=1:" target="_blank">Find out how to enable cookies</a></p>

        <p>Once you've enabled your cookies, please <a href="/">continue to home page</a> and you should have access to the service.</p>

    </div>
</div>