<?php $this->layout('layout::default') ?>

<div class="grid-row">
    <div class="column-two-thirds">

        <div class="govuk-box-highlight">
            <h1 class="bold-large">Claim submitted for <?= $this->e($name) ?></h1>
            <p>
                Your reference <br>
                <strong class="heading-medium"><?= $this->e($reference) ?></strong>
            </p>
            <?php if (!empty($contact['email'])): ?>
                <p>Email confirmation sent to <span class="bold"><?= $this->e($contact['email']) ?></span></p>
            <?php endif ?>
            <?php if (!empty($contact['mobile'])): ?>
                <p>Text message confirmation sent to <span class="bold"><?= $this->e($contact['mobile']) ?></span></p>
            <?php endif ?>
        </div>

        <h2 class="heading-medium">What happens next</h2>
        
        <p>We will let you know when your claim is approved or if we need more information.</p>
        
        <div class="panel panel-border-wide">
            <p>
            Current processing time: <?= $this->e($processingTime) ?>.
            </p>
        </div>

        <p>Your refund will be paid by <?= $this->e(date('j F Y', strtotime('+'.$processingTime))) ?>, if your claim is approved.</p>
        
        <h2 class="heading-medium">Tell the attorneys</h2>

        <p>Please tell all attorneys you've applied for a refund. It can slow things down if we get more than one claim.</p>

        <p>
            <a href="<?= $this->url('eligibility.when') ?>" class="button">Start a new claim</a>
        </p>

    </div>
</div>
