<?php
$title = 'Donor details';
$this->layout('layout::standard', [
    'title' => $title,
]);
?>

<?php $this->insert('snippet::error-summary', [ 'form'=>$form ]) ?>

<p>For: <?= $this->e($type) ?></p>


<form class="form" action="<?= $form->getAttribute('action') ?? $this->url() ?>" method="<?= $this->e(strtolower($form->getAttribute('method'))) ?>">

    <div class="form-group">
        <fieldset>
            <legend class="visually-hidden">Donor's Name</legend>

            <?php $this->insert('snippet::input-text', [
                'formElement' => $form->get('title'),
                'formLabel' => 'Title',
                'formType' => 'text',
                'formLabelBold' => false
            ]) ?>

            <?php $this->insert('snippet::input-text', [
                'formElement' => $form->get('first'),
                'formLabel' => 'First names',
                'formType' => 'text',
                'formLabelBold' => false
            ]) ?>

            <?php $this->insert('snippet::input-text', [
                'formElement' => $form->get('last'),
                'formLabel' => 'Last name',
                'formType' => 'text',
                'formLabelBold' => false
            ]) ?>

        </fieldset>
    </div>

    <div class="form-group">
        <fieldset>
            <legend class="visually-hidden">Donor's data of birth</legend>

            <?php $this->insert('snippet::input-text', [
                'formElement' => $form->get('day'),
                'formLabel' => 'Day',
                'formType' => 'number',
                'formLabelBold' => false
            ]) ?>

            <?php $this->insert('snippet::input-text', [
                'formElement' => $form->get('month'),
                'formLabel' => 'Month',
                'formType' => 'number',
                'formLabelBold' => false
            ]) ?>

            <?php $this->insert('snippet::input-text', [
                'formElement' => $form->get('year'),
                'formLabel' => 'Year',
                'formType' => 'number',
                'formLabelBold' => false
            ]) ?>

        </fieldset>
    </div>

    <div class="form-group">
        <input class="button" type="submit" value="Continue">
    </div>

</form>


