<?php
$title = 'About the donor';
$this->layout('layout::standard', [
    'title' => $title,
    'form' => $form
]);

$form->setAttribute('method', 'get');
$form->setAttribute('action', $this->url('eligibility.deceased.answer'));
?>

<?php $this->insert('snippet::error-summary', [ 'form'=>$form ]) ?>

<p>We need to know if the donor has died. This is because the refund is for the donor, even if you're making the claim on their behalf.</p>

<form class="form" action="<?= $form->getAttribute('action') ?? $this->url() ?>" method="<?= $this->e(strtolower($form->getAttribute('method'))) ?>">

    <?php $this->insert('snippet::input-radio', [
        'formElement' => $form->get('donor-deceased'),
        'question' => $title,
        'options' => [
            'no' => [
                'optionLabel' => 'The donor is alive',
            ],
            'yes' => [
                'optionLabel' => 'The donor has died',
            ],
        ],
    ])
    ?>

    <div class="form-group">
        <input class="button" type="submit" value="Continue">
    </div>

</form>


