<?php
$title = ($applicant == 'donor') ? 'Your details (donor)' : 'Donor details';
$this->layout('layout::standard', [
    'title' => $title,
    'pageTitle' => (!empty($form->getMessages())) ? "Error: {$title}" : null,
]);


// Error messages are in a snippet as shared between donor and attorney page
$this->fetch('snippet::actor-errors', [
    'firstPerson' => ($applicant == 'donor')
]);

?>

<?php $this->start('error-summary') ?>
    <?php $this->insert('snippet::error-summary', [ 'form'=>$form ]) ?>
<?php $this->stop() ?>

<form class="form" action="<?= $form->getAttribute('action') ?? $this->url() ?>" method="<?= $this->e(strtolower($form->getAttribute('method'))) ?>">

    <?php $this->insert('snippet::form-csrf', [ 'form'=>$form ]) ?>

    <fieldset>
        <legend class="form-label-bold"><?= ($applicant == 'donor') ? "Name" : "Donor name" ?></legend>

        <?php $this->insert('snippet::input-text', [
            'formElement' => $form->get('title'),
            'formLabel' => 'Title',
            'formType' => 'text',
            'formLabelBold' => false,
            'additionFormControlClass' => 'form-control-1-8'
        ]) ?>

        <?php $this->insert('snippet::input-text', [
            'formElement' => $form->get('first'),
            'formLabel' => 'First names',
            'formType' => 'text',
            'formLabelBold' => false
        ]) ?>

        <?php $this->insert('snippet::input-text', [
            'formElement' => $form->get('last'),
            'formLabel' => 'Last name',
            'formType' => 'text',
            'formLabelBold' => false
        ]) ?>

    </fieldset>

    <div class="form-group">
        <div class="multiple-choice" data-target="name-on-poa">
            <?php $element = $form->get('poa-name-different'); ?>
            <input
                id="name-on-poa-checkbox"
                name="<?= $element->getName(); ?>"
                type="checkbox"
                value="yes"
                <?= ($element->getValue()=='yes') ? ' checked="checked"' : '' ?>
            >
            <label for="name-on-poa-checkbox">
                <?= ($applicant == 'donor') ? "My" : "Their" ?> name is different on the power of attorney documents
            </label>
        </div>

        <div class="panel panel-border-narrow js-hidden" id="name-on-poa">
            <fieldset>
                <legend class="form-label-bold"><?= ($applicant == 'donor') ? "Name" : "Donor name" ?> on power of attorney documents</legend>

                <?php $this->insert('snippet::input-text', [
                    'formElement' => $form->get('poa-title'),
                    'formLabel' => 'Title',
                    'formType' => 'text',
                    'formLabelBold' => false,
                    'additionFormControlClass' => 'form-control-1-8'
                ]) ?>

                <?php $this->insert('snippet::input-text', [
                    'formElement' => $form->get('poa-first'),
                    'formLabel' => 'First names',
                    'formType' => 'text',
                    'formLabelBold' => false
                ]) ?>

                <?php $this->insert('snippet::input-text', [
                    'formElement' => $form->get('poa-last'),
                    'formLabel' => 'Last name',
                    'formType' => 'text',
                    'formLabelBold' => false
                ]) ?>

            </fieldset>
        </div>
    </div>

    <?php $this->insert('snippet::input-dob', [
        'formLabel' => ($applicant == 'donor') ? "Date of birth" : "Donor date of birth",
        'formElement' => $form->get('dob'),
    ]) ?>

    <fieldset>
        <legend class="form-label-bold"><?= ($applicant == 'donor') ? "Current address" : "Current donor address" ?></legend>

        <?php $this->insert('snippet::input-text', [
            'formElement' => $form->get('address-1'),
            'formLabel' => 'Address line 1',
            'formType' => 'text',
            'formLabelBold' => false,
        ]) ?>

        <?php $this->insert('snippet::input-text', [
            'formElement' => $form->get('address-2'),
            'formLabel' => 'Address line 2 (optional)',
            'formType' => 'text',
            'formLabelBold' => false,
        ]) ?>

        <?php $this->insert('snippet::input-text', [
            'formElement' => $form->get('address-3'),
            'formLabel' => 'Address line 3 (optional)',
            'formType' => 'text',
            'formLabelBold' => false,
        ]) ?>

        <?php $this->insert('snippet::input-text', [
            'formElement' => $form->get('address-postcode'),
            'formLabel' => 'Postcode',
            'formType' => 'text',
            'formLabelBold' => false,
        ]) ?>


    </fieldset>

    <div class="form-group">
        <input class="button" type="submit" value="Continue">
    </div>

</form>


