<?php
$title = ($applicant == 'donor') ? 'Is your name different on your document?' : 'Is the donor\'s different on the document?';
$this->layout('layout::standard', [
    'title' => $title,
]);

?>

<?php $this->insert('snippet::error-summary', [ 'form'=>$form ]) ?>

<p>Donor details on POA</p>


<form class="form" action="<?= $form->getAttribute('action') ?? $this->url() ?>" method="<?= $this->e(strtolower($form->getAttribute('method'))) ?>">

    <?php $this->insert('snippet::form-csrf', [ 'form'=>$form ]) ?>

    <?php $this->insert('snippet::input-radio', [
        'formElement' => $form->get('different-name-on-poa'),
        'question' => $title,
        'options' => [
            'no' => [
                'optionLabel' => "No, my name is {$name['title']} {$name['first']} {$name['last']} on the document"
            ],
            'yes' => [
                'optionLabel' => "Yes, it is different",
                'dataTarget' => 'poa-name',
                'dataTargetMarkup' => $this->fetch('snippet::input-name', [
                    'title' => 'Name on document',
                    'form' => $form,
                ])
            ],
        ],
    ])
    ?>

    <div class="form-group">
        <input class="button" type="submit" value="Continue">
    </div>

</form>