<?php $this->layout('layout::default', ['title' => 'Home']) ?>

<p>Logged in as <?= $caseworker->getName(); ?></p>

<h2>Your outstanding claims</h2>

<table>
    <thead>
    <tr>
        <th>Refund case / ref number</th>
        <th>Donor name</th>
        <th>Date received</th>
        <th>Date claim modified</th>
        <th></th>
    </tr>
    </thead>
    <tbody>
        <?php if (count($caseworker->getRefundCases())) { ?>
            <?php foreach ($caseworker->getRefundCases() as $refundCase) { ?>
                <tr>
                    <td><?= $refundCase->getReferenceNumber() ?></td>
                    <td><?= $refundCase->getDonorName() ?></td>
                    <td><?= $refundCase->getReceivedDateTime()->format('d/m/Y') ?></td>
                    <td><?= ($refundCase->getUpdatedDateTime() ?: $refundCase->getReceivedDateTime())->format('d/m/Y') ?></td>
                    <td>View</td>
                </tr>
            <?php } ?>
        <?php } else { ?>
            <tr>
                <td colspan="5">No claims</td>
            </tr>
        <?php } ?>
    </tbody>
</table>

<h2>All claims</h2>

<table>
    <thead>
        <tr>
            <th>Refund case / ref number</th>
            <th>Donor name</th>
            <th>Date received</th>
            <th>Date claim modified</th>
            <th>Status</th>
        </tr>
    </thead>
    <tbody>
        <?php if (count($refundCases)) { ?>
            <?php foreach ($refundCases as $refundCase) { ?>
                <tr>
                    <td><?= $refundCase->getReferenceNumber() ?></td>
                    <td><?= $refundCase->getDonorName() ?></td>
                    <td><?= $refundCase->getReceivedDateTime()->format('d/m/Y') ?></td>
                    <td><?= ($refundCase->getUpdatedDateTime() ?: $refundCase->getReceivedDateTime())->format('d/m/Y') ?></td>
                    <td><?= $refundCase->getStatus() ?></td>
                </tr>
            <?php } ?>
        <?php } else { ?>
            <tr>
                <td colspan="5">No claims</td>
            </tr>
        <?php } ?>
    </tbody>
</table>

<p><a href="/caseworker">Case worker user page</a></p>
<p><a href="/reporting">Reporting user page</a></p>
<p><a href="/refund">Refund manager user page</a></p>
<p><a href="/admin">Admin user page</a></p>
<p><a href="/download">Download SSCL spreadsheet</a></p>

<p><a href="sign-out">Sign out</a></p>
