<?php $this->layout('layout::standard', ['title'=>'Sorry, you can\'t claim online']) ?>

<p>
If the donor has died, the executor of the will or administrator of the estate, needs to send us some extra information before we can start the claim.
</p>

<p>
Please send us photocopies or scans of the donor’s:
</p>

<ul class="list list-bullet">
    <li>death certificate</li>
    <li>will or the grant of representation (for example, a grant of probate or letters of administration)</li>
</ul>

<p>
Make sure you include:
</p>

<ul class="list list-bullet">
    <li>your name</li>
    <li>your contact telephone number, email and postal address</li>
    <li>the donor’s name</li>
    <li>the case reference number (if you know it)</li>
</ul>

<p>
You can email the information and documents to <a href="mailto:poarefunds@justice.gsi.gov.uk">poarefunds@justice.gsi.gov.uk</a> or post it to POA Refunds Team, 7th Floor, Office of the Public Guardian, Po Box 16185, Birmingham, B2 2WH.
</p>

<p>
When we’ve received these documents we’ll contact you to complete a refund claim over the phone.
</p>