<?php $this->layout('layout::standard', ['title'=>'Sorry, you can\'t claim online']) ?>

<p>
Please contact the Refunds Helpline.
</p>

<p>
We will discuss your situation and let you know who is entitled 
to claim the refund and what they need to do.
</p> 

<h2 class="heading-medium">Refunds Helpline</h2>

<address>
    <p>
        Email: <a href="mailto:refunds@opg.gov.uk">refunds@opg.gov.uk</a><br>
        Telephone: 0300 123 1122<br>
        Textphone: 0300 123 1123<br>
        Monday to Friday, 9am to 5pm<br>
        <a href="https://www.gov.uk/call-charges">Find out about call charges</a>
    </p>
</address>

<div class="panel panel-border-wide">
    <p>
    The deadline for claims is 28 February 2021.
    </p>
</div>
