<?php $this->layout('layout::default', ['title' => 'Notify'])

/**
 * @var \App\Form\Notify $form
 */

?>

<h2 class="heading-medium heading-refunds">Notify claimants of the outcome</h2>

<div class="grid-row">
    <div class="column-three-fifths">

        <?php $this->insert('snippet::flash-messages', ['messages' => $messages]) ?>

        <?php $this->insert('snippet::error-summary', [ 'form'=>$form ]) ?>

        <form method="post" class="form">

            <?php $this->insert('snippet::input-hidden', ['formElement' => $form->get('secret')]) ?>

            <p>Clicking 'Notify' will send an outcome notification email and a text to all claimants who have not yet been notified.</p>
            <p>It will notify any claimant whose claim was either rejected yesterday or was added to today's SOP1 spreadsheet.</p>
            <p>It will only notify claimants who have supplied a valid email address or mobile number</p>
            <p>Do you wish to proceed?</p>

            <div class="form-group">
                <input type='submit' class="button" name='submit' value='Notify'>
                <a class="button button-link" href="<?= $this->generateUrl('refund') ?>">Cancel</a>
            </div>

        </form>

    </div>
</div>