<?php $this->layout('layout::default', ['title' => 'Change password']) ?>

<?php $this->insert('snippet::error-summary', ['form' => $form]) ?>

<div class="grid-row">
    <div class="column-full">

        <h2 class="heading-medium heading-refunds">Change password</h2>

        <form method="post" class="form">

            <?php $this->insert('snippet::input-hidden', ['formElement' => $form->get('secret')]) ?>

            <fieldset>

                <?php $this->insert('snippet::input-text', [
                    'formElement' => $form->get('password'),
                    'formLabel' => 'Password',
                    'formType' => 'password',
                    'formLabelBold' => false
                ]) ?>

                <?php $this->insert('snippet::input-text', [
                    'formElement' => $form->get('confirm-password'),
                    'formLabel' => 'Confirm password',
                    'formType' => 'password',
                    'formLabelBold' => false
                ]) ?>

            </fieldset>

            <p>
                <input type="submit" class="button" value="Save" />
                <a class="button button-secondary" href="<?= $this->generateUrl('home') ?>">Cancel</a>
            </p>

        </form>
    </div>
</div>
