<?php $this->layout('layout::default', ['title' => 'Change password']) ?>

<div class="grid-row">
    <div class="column-full">

        <h2 class="heading-medium heading-refunds">Password changed</h2>

        <p>Your password has been changed.</p>

        <?php if (!$loggedIn) { ?>
            <p>You may now sign in to your account.</p>
        <?php } ?>

        <p>
            <a class="button" href="<?= $this->generateUrl('home') ?>">Continue</a>
        </p>

    </div>
</div>
