<?php $this->layout('layout::default', ['title' => 'Password reset expired']); ?>

<div class="grid-row">
    <div class="column-full">

        <h2 class="heading-medium heading-refunds">Password reset expired</h2>

        <p>Your password reset request has expired.</p>

        <p><a class="button" href="<?= $this->generateUrl('password.reset') ?>">Reset password again</a></p>

    </div>
</div>
