<?php $this->layout('layout::default', ['title' => 'Reset password']);

$this->addErrorMap([
    'email' => [
        'required' => [
            'summary'   => 'Please enter a valid gov.uk email address',
            'field'     => 'Please enter a valid gov.uk email address',
        ],
        'invalid-email' => [
            'summary'   => 'Please enter a valid gov.uk email address',
            'field'     => 'Please enter a valid gov.uk email address',
        ],
        'email-mismatch' => [
            'summary'   => 'The email addresses did not match',
            'field'     => 'The email addresses did not match',
        ],
    ],
]);
?>

<div class="grid-row">
    <div class="column-full">

        <form method="post" class="form" action="<?= $this->generateUrl('password.reset') ?>">

            <fieldset>

                <legend>
                    <h1 class="heading-xlarge">Reset your password</h1>
                </legend>

                <?php $this->insert('snippet::error-summary', ['form' => $form]) ?>

                <?php $this->insert('snippet::input-hidden', ['formElement' => $form->get('secret')]) ?>

                <?php $this->insert('snippet::input-text', [
                    'formElement' => $form->get('email'),
                    'formLabel' => 'Email address',
                    'formType' => 'text',
                    'formLabelBold' => false
                ]) ?>

                <?php $this->insert('snippet::input-text', [
                    'formElement' => $form->get('confirm-email'),
                    'formLabel' => 'Confirm your email address',
                    'formType' => 'text',
                    'formLabelBold' => false
                ]) ?>

            </fieldset>

            <div class="form-group">
                <input class="button" type="submit" value="Email me the link">
                <a class="button button-secondary" href="<?= $this->generateUrl('home') ?>">Cancel</a>
            </div>

        </form>

    </div>
</div>
