<?php $this->layout('layout::default', ['title' => 'Change password']);

$this->addErrorMap([
    'password' => [
        'required' => [
            'summary'   => 'Please enter a password',
            'field'     => 'Please enter a password',
        ],
        'too-short' => [
            'summary'   => 'Password must be at least eight characters long',
            'field'     => 'Password must be at least eight characters long',
        ],
        'must-include-digit' => [
            'summary'   => 'Password must include at least one digit (0-9)',
            'field'     => 'Password must include at least one digit (0-9)',
        ],
        'must-include-upper-case' => [
            'summary'   => 'Password must include at least one capital letter (A-Z)',
            'field'     => 'Password must include at least one capital letter (A-Z)',
        ],
        'password-mismatch' => [
            'summary'   => 'The passwords did not match',
            'field'     => 'The passwords did not match',
        ],
    ],
]);
?>

<?php $this->insert('snippet::error-summary', ['form' => $form]) ?>

<div class="grid-row">
    <div class="column-full">

        <h2 class="heading-medium heading-refunds">Change password</h2>

        <form method="post" class="form">

            <?php $this->insert('snippet::input-hidden', ['formElement' => $form->get('secret')]) ?>

            <fieldset>

                <?php $this->insert('snippet::input-text', [
                    'formElement' => $form->get('password'),
                    'formLabel' => 'Password',
                    'formType' => 'password',
                    'formLabelBold' => false,
                    'disableAutocomplete' => true
                ]) ?>

                <?php $this->insert('snippet::input-text', [
                    'formElement' => $form->get('confirm-password'),
                    'formLabel' => 'Confirm password',
                    'formType' => 'password',
                    'formLabelBold' => false,
                    'disableAutocomplete' => true
                ]) ?>

            </fieldset>

            <p>
                <input type="submit" class="button" value="Save" />
                <a class="button button-secondary" href="<?= $this->generateUrl('home') ?>">Cancel</a>
            </p>

        </form>
    </div>
</div>
