<?php
use Opg\Refunds\Caseworker\DataModel\Applications\AssistedDigital as AssistedDigitalModel;
use Opg\Refunds\Caseworker\DataModel\PhoneClaimTypeFormatter;

$this->layout('layout::default', ['title' => 'Start phone claim'])

/**
 * @var \App\Form\PhoneClaim $form
 */
?>

<h2 class="heading-medium heading-refunds">Start phone claim</h2>

<div class="grid-row">
    <div class="column-three-fifths">

        <form method="post" class="form" target="_blank">

            <?php $this->insert('snippet::input-hidden', ['formElement' => $form->get('secret')]) ?>

            <?php $this->insert('snippet::input-multi', [
                'formElement' => $form->get('type'),
                'question' => 'Reason for the phone call',
                'options' => [
                    AssistedDigitalModel::TYPE_ASSISTED_DIGITAL =>[
                        'optionLabel' => PhoneClaimTypeFormatter::getPhoneClaimTypeText(AssistedDigitalModel::TYPE_ASSISTED_DIGITAL),
                        'optionLabelSuffix' => 'The caller can\'t make the claim online because they don\'t have internet access or the necessary digital skills'
                    ],
                    AssistedDigitalModel::TYPE_REFUSE_CLAIM_ONLINE =>[
                        'optionLabel' => PhoneClaimTypeFormatter::getPhoneClaimTypeText(AssistedDigitalModel::TYPE_REFUSE_CLAIM_ONLINE),
                        'optionLabelSuffix' => 'The caller is able to claim online, but doesn\'t want to. This option should only be used in exceptional cases, for example, if the caller has a complaint or doesn\'t want to enter their bank details'
                    ],
                    AssistedDigitalModel::TYPE_CHEQUE =>[
                        'optionLabel' => PhoneClaimTypeFormatter::getPhoneClaimTypeText(AssistedDigitalModel::TYPE_CHEQUE),
                        'optionLabelSuffix' => 'This option should only be used in exceptional cases, for example, if the caller won\'t provide their bank details or if the donor only has a foreign bank account'
                    ],
                    AssistedDigitalModel::TYPE_DEPUTY =>[
                        'optionLabel' => PhoneClaimTypeFormatter::getPhoneClaimTypeText(AssistedDigitalModel::TYPE_DEPUTY),
                        'optionLabelSuffix' => 'The LPA or EPA has been cancelled and a deputy is now managing the donor\'s affairs'
                    ],
                    AssistedDigitalModel::TYPE_DONOR_DECEASED =>[
                        'optionLabel' => PhoneClaimTypeFormatter::getPhoneClaimTypeText(AssistedDigitalModel::TYPE_DONOR_DECEASED),
                        'optionLabelSuffix' => 'The donor has died'
                    ],
                ],
            ])
            ?>

            <div class="form-group">
                <input type='submit' class="button" name='submit' value='Start phone claim'>
                <a class="button button-link" href="<?= $this->generateUrl('home') ?>">Cancel</a>
            </div>

        </form>

    </div>
</div>
