<?php $this->layout('layout::three-column', ['title' => 'Claim', 'claim' => $claim]);

/**
 * @var \Opg\Refunds\Caseworker\DataModel\Cases\Claim $claim
 * @var \Opg\Refunds\Caseworker\DataModel\Cases\Poa $poa
 */
?>

<?php $this->start('left-sidebar') ?>
<?php $this->insert('snippet::all-details', ['claim' => $claim]) ?>
<?php $this->stop() ?>

<?php $this->start('right-sidebar') ?>
<?php $this->insert('snippet::case-numbers', ['claim' => $claim]) ?>
<?php $this->stop() ?>

<h2 class="heading-medium">Delete POA</h2>

<form method="post" class="form">

    <p>Are you sure you want to delete the POA with case number: <?= $poa->getCaseNumber() ?>?</p>

    <div class="form-group">
        <input type='submit' class="button button-secondary" name='submit' value='Yes'>
        <a class="button button-secondary" href="<?= $cancelUrl ?>">No</a>
    </div>

</form>