<?php $this->layout('layout::three-column', ['title' => 'Claim', 'claim' => $claim]);

/**
 * @var \Opg\Refunds\Caseworker\DataModel\Cases\Claim $claim
 * @var \App\Form\Poa $form
 * @var string $system
 */
?>

<?php $this->start('left-sidebar') ?>
<?php $this->insert('snippet::all-details', ['claim' => $claim]) ?>
<?php $this->stop() ?>

<?php $this->start('right-sidebar') ?>
<?php $this->insert('snippet::case-numbers', ['claim' => $claim]) ?>
<?php $this->stop() ?>

<?php $this->insert('snippet::error-summary', [ 'form'=>$form ]) ?>

<?php if ($system === \App\Form\Poa::SYSTEM_SIRIUS) { ?>
    <h2 class="heading-medium">Sirius power of attorney details</h2>
<?php } elseif ($system === \App\Form\Poa::SYSTEM_MERIS) { ?>
    <h2 class="heading-medium">Meris power of attorney details</h2>
<?php } ?>

<?php $this->insert('snippet::poa-form', [
    'form'      => $form,
    'claim'     => $claim,
    'system'    => $system,
    'deleteUrl' => isset($deleteUrl) ? $deleteUrl : null
]) ?>
