<?php $this->layout('layout::three-column', ['title' => 'Claim', 'claim' => $claim]);

/**
 * @var \Opg\Refunds\Caseworker\DataModel\Cases\Claim $claim
 * @var \App\Form\AbstractForm $form
 */

$this->addErrorMap([
    'message' => [
        'required' => [
            'summary'   => 'Please enter a user log message',
            'field'     => 'Enter a user log message'
        ]
    ]
]);
?>

<?php $this->start('left-sidebar') ?>
<?php $this->insert('snippet::all-details', ['claim' => $claim]) ?>
<?php $this->stop() ?>

<?php $this->start('right-sidebar') ?>
<?php $this->insert('snippet::case-numbers', ['claim' => $claim]) ?>
<?php $this->stop() ?>

<?php $this->insert('snippet::error-summary', [ 'form'=>$form ]) ?>

<h2 class="heading-medium">Meris power of attorney details</h2>

<form method="post" class="form">

    <?php $this->insert('snippet::form-csrf', ['form' => $form]) ?>

    <div class="form-group">
        <input type="submit" class="button" value="Save and return to claim" />
        <input type="submit" class="button" value="Save and add another" />
    </div>

    <a href="/claim/<?= $claim->getId() ?>">Cancel</a>

</form>
