<?php $this->layout('layout::three-column', ['title' => 'Claim', 'claim' => $claim]);

/**
 * @var \Opg\Refunds\Caseworker\DataModel\Cases\Claim $claim
 * @var \App\Form\AbstractForm $form
 */

$this->addErrorMap([
    'message' => [
        'required' => [
            'summary'   => 'Please enter a user log message',
            'field'     => 'Enter a user log message'
        ]
    ]
]);
?>

<?php $this->start('left-sidebar') ?>
<?php $this->insert('snippet::all-details', ['claim' => $claim]) ?>
<?php $this->stop() ?>

<?php $this->start('right-sidebar') ?>
<?php $this->insert('snippet::case-numbers', ['claim' => $claim]) ?>
<?php $this->stop() ?>

<?php $this->insert('snippet::error-summary', [ 'form'=>$form ]) ?>

<h2 class="heading-medium">Meris power of attorney details</h2>

<?php $this->insert('snippet::poa-form', [
    'form'  => $form,
    'claim' => $claim
]) ?>
