<?php
$title = 'Postcodes on power of attorney';
$this->layout('layout::standard', [
    'title' => $title,
]);
?>

<?php $this->insert('snippet::error-summary', [ 'form'=>$form ]) ?>

<p>We need at least one postcode from the power of attorney.</p>

<div class="panel panel-border-wide">
    <p>Postcodes are on the registered document.</p>
</div>

<form class="form" action="<?= $form->getAttribute('action') ?? $this->url() ?>" method="<?= $this->e(strtolower($form->getAttribute('method'))) ?>">

    <?php $this->insert('snippet::form-csrf', [ 'form'=>$form ]) ?>
    
    <?php $this->insert('snippet::input-text', [
        'formElement' => $form->get('donor-postcode'),
        'formLabel' => 'Donor postcode',
        'formType' => 'text',
        'formHint' => 'When power of attorney was made',
        'formLabelBold' => true
    ]) ?>

    <?php $this->insert('snippet::input-text', [
        'formElement' => $form->get('attorney-postcode'),
        'formLabel' => 'Attorney postcode',
        'formType' => 'text',
        'formHint' => 'When power of attorney was made',
        'formLabelBold' => true
    ]) ?>

    <div class="form-group">
        <input class="button" type="submit" value="Continue">
    </div>

</form>