<?php $this->layout('layout::default', ['title' => 'Refunds']) ?>

<div class="grid-row">
    <div class="column-full">

        <h2 class="heading-medium heading-refunds">Refunds</h2>

        <p><a href="<?= $this->generateUrl('download') ?>">Download Today's SSCL spreadsheet</a></p>

        <h2 class="heading-medium heading-refunds">Historic Refunds</h2>

        <ul>
            <li><a href="<?= $this->generateUrl('download', ['date' => '2017-10-05']) ?>">05 October 2017</a></li>
        </ul>

    </div>
</div>
