<?php use Opg\Refunds\Caseworker\DataModel\Cases\Claim as ClaimModel;

$this->layout('layout::default', ['title' => 'Reporting']);

/**
 * @var array $reports
 */

$claim = $reports['claim'];
$rejectionReason = $reports['rejectionReason'];
$duplicateBankDetail = $reports['duplicateBankDetail'];
$refund = $reports['refund'];
?>

<div class="grid-row">
    <div class="column-full">

        <h1 class="heading-medium heading-refunds">Reporting</h1>

        <p>Generated <?= $reports['generated'] ?></p>

        <h2 class="heading-small heading-refunds">Claims</h2>

        <?php $claimAllTime = $claim['allTime']; ?>

        <h3 class="heading-small">Totals</h3>

        <table>
            <thead>
                <tr>
                    <th class="numeric">Date</th>
                    <th class="numeric">Received</th>
                    <th class="numeric">Pending</th>
                    <th class="numeric">In progress</th>
                    <th class="numeric">Accepted</th>
                    <th class="numeric">Rejected</th>
                </tr>
            </thead>
            <tbody>
                <tr>
                    <td class="numeric">All time</td>
                    <td class="numeric"><?= $claimAllTime['total'] ?></td>
                    <td class="numeric"><?= $claimAllTime[ClaimModel::STATUS_PENDING] ?></td>
                    <td class="numeric"><?= $claimAllTime[ClaimModel::STATUS_IN_PROGRESS] ?></td>
                    <td class="numeric"><?= "{$claimAllTime[ClaimModel::STATUS_ACCEPTED]} ({$this->getPercentage($claimAllTime['total'], $claimAllTime[ClaimModel::STATUS_ACCEPTED])})" ?></td>
                    <td class="numeric"><?= "{$claimAllTime[ClaimModel::STATUS_REJECTED]} ({$this->getPercentage($claimAllTime['total'], $claimAllTime[ClaimModel::STATUS_REJECTED])})" ?></td>
                </tr>
            </tbody>
        </table>

        <?php $claimByDay = $claim['byDay']; ?>

        <h3 class="heading-small">By Day - last <?= count($claimByDay) ?> days</h3>

        <table>
            <thead>
                <tr>
                    <th class="numeric" style="width: 25%">Date</th>
                    <th class="numeric" style="width: 25%">Received</th>
                    <th class="numeric" style="width: 25%">Accepted</th>
                    <th class="numeric" style="width: 25%">Rejected</th>
                </tr>
            </thead>
            <tbody>
            <?php foreach ($claimByDay as $day => $counts){ ?>
                <tr>
                    <td class="numeric"><?= $day ?></td>
                    <td class="numeric"><?= $counts['total'] ?></td>
                    <td class="numeric"><?= $counts[ClaimModel::STATUS_ACCEPTED] ?></td>
                    <td class="numeric"><?= $counts[ClaimModel::STATUS_REJECTED] ?></td>
                </tr>
            <?php } ?>
            </tbody>
        </table>

        <?php $claimByWeek = $claim['byWeek']; ?>

        <h3 class="heading-small">By week - last <?= count($claimByWeek) ?> weeks</h3>

        <table>
            <thead>
                <tr>
                    <th class="numeric" style="width: 25%">Date</th>
                    <th class="numeric" style="width: 25%">Received</th>
                    <th class="numeric" style="width: 25%">Accepted</th>
                    <th class="numeric" style="width: 25%">Rejected</th>
                </tr>
            </thead>
            <tbody>
            <?php foreach ($claimByWeek as $week => $counts){ ?>
                <tr>
                    <td class="numeric"><?= $week ?></td>
                    <td class="numeric"><?= $counts['total'] ?></td>
                    <td class="numeric"><?= $counts[ClaimModel::STATUS_ACCEPTED] ?></td>
                    <td class="numeric"><?= $counts[ClaimModel::STATUS_REJECTED] ?></td>
                </tr>
            <?php } ?>
            </tbody>
        </table>

        <?php $claimByMonth = $claim['byMonth']; ?>

        <h3 class="heading-small">By month - last <?= count($claimByMonth) ?> months</h3>

        <table>
            <thead>
                <tr>
                    <th class="numeric" style="width: 25%">Date</th>
                    <th class="numeric" style="width: 25%">Received</th>
                    <th class="numeric" style="width: 25%">Accepted</th>
                    <th class="numeric" style="width: 25%">Rejected</th>
                </tr>
            </thead>
            <tbody>
            <?php foreach ($claimByMonth as $month => $counts){ ?>
                <tr>
                    <td class="numeric"><?= $month ?></td>
                    <td class="numeric"><?= $counts['total'] ?></td>
                    <td class="numeric"><?= $counts[ClaimModel::STATUS_ACCEPTED] ?></td>
                    <td class="numeric"><?= $counts[ClaimModel::STATUS_REJECTED] ?></td>
                </tr>
            <?php } ?>
            </tbody>
        </table>

        <h2 class="heading-small heading-refunds">Claim source</h2>

        <h3 class="heading-small">Totals</h3>

        <table>
            <thead>
            <tr>
                <th class="numeric" style="width: 20%">Date</th>
                <th class="numeric" style="width: 20%">Donor</th>
                <th class="numeric" style="width: 20%">Attorney</th>
                <th class="numeric" style="width: 20%">Assisted digital</th>
                <th class="numeric" style="width: 20%">Donor deceased</th>
            </tr>
            </thead>
            <tbody>
            <tr>
                <td class="numeric">All time</td>
                <td class="numeric">0</td>
                <td class="numeric">0</td>
                <td class="numeric">0</td>
                <td class="numeric">0</td>
            </tr>
            </tbody>
        </table>

        <h3 class="heading-small">By month - last 12 months</h3>

        <table>
            <thead>
            <tr>
                <th class="numeric" style="width: 20%">Date</th>
                <th class="numeric" style="width: 20%">Donor</th>
                <th class="numeric" style="width: 20%">Attorney</th>
                <th class="numeric" style="width: 20%">Assisted digital</th>
                <th class="numeric" style="width: 20%">Donor deceased</th>
            </tr>
            </thead>
            <tbody>
            <?php
            $month = new DateTime('last month');
            for ($i = 0; $i < 12; $i++) { ?>
                <tr>
                    <td class="numeric"><?= date('F Y', $month->getTimestamp()) ?></td>
                    <td class="numeric">0</td>
                    <td class="numeric">0</td>
                    <td class="numeric">0</td>
                    <td class="numeric">0</td>
                </tr>
                <?php
                $month = $month->sub(new DateInterval('P1M'));
            } ?>
            </tbody>
        </table>

        <h2 class="heading-small heading-refunds">Rejection reasons</h2>

        <?php $rejectionReasonAllTime = $rejectionReason['allTime']; ?>

        <h3 class="heading-small">Totals</h3>

        <table>
            <thead>
            <tr>
                <th class="numeric" style="width: 20%">No eligible POAs found</th>
                <th class="numeric" style="width: 20%">POA already refunded</th>
                <th class="numeric" style="width: 20%">No fees paid</th>
                <th class="numeric" style="width: 20%">Details not verified</th>
                <th class="numeric" style="width: 20%">Other</th>
            </tr>
            </thead>
            <tbody>
            <tr>
                <td class="numeric"><?= $rejectionReasonAllTime[ClaimModel::REJECTION_REASON_NO_ELIGIBLE_POAS_FOUND] ?></td>
                <td class="numeric"><?= $rejectionReasonAllTime[ClaimModel::REJECTION_REASON_PREVIOUSLY_REFUNDED] ?></td>
                <td class="numeric"><?= $rejectionReasonAllTime[ClaimModel::REJECTION_REASON_NO_FEES_PAID] ?></td>
                <td class="numeric"><?= $rejectionReasonAllTime[ClaimModel::REJECTION_REASON_CLAIM_NOT_VERIFIED] ?></td>
                <td class="numeric"><?= $rejectionReasonAllTime[ClaimModel::REJECTION_REASON_OTHER] ?></td>
            </tr>
            </tbody>
        </table>

        <h2 class="heading-small heading-refunds">Duplicate bank details</h2>

        <?php $duplicateBankDetailAllTime = $duplicateBankDetail['allTime']; ?>

        <h3 class="heading-small">Total</h3>

        <table>
            <thead>
            <tr>
                <th class="numeric" style="width: 50%">Number of times bank details used</th>
                <th class="numeric" style="width: 50%">Frequency</th>
            </tr>
            </thead>
            <tbody>
            <?php foreach ($duplicateBankDetailAllTime as $timesUsed => $frequency){ ?>
                <tr>
                    <td class="numeric"><?= $timesUsed ?></td>
                    <td class="numeric"><?= $frequency ?></td>
                </tr>
            <?php } ?>
            </tbody>
        </table>

        <h2 class="heading-small heading-refunds">Refunds</h2>

        <?php $refundAllTime = $refund['allTime']; ?>

        <h3 class="heading-small">Totals</h3>

        <table>
            <thead>
            <tr>
                <th class="numeric" style="width: 20%">Date</th>
                <th class="numeric" style="width: 20%">Number of spreadsheets</th>
                <th class="numeric" style="width: 20%">Number of refunds by bank transfer</th>
                <th class="numeric" style="width: 20%">Number of refunds by cheque</th>
                <th class="numeric" style="width: 20%">Total refund value</th>
            </tr>
            </thead>
            <tbody>
            <tr>
                <td class="numeric">All time</td>
                <td class="numeric"><?= $refundAllTime['number_of_spreadsheets'] ?></td>
                <td class="numeric"><?= $refundAllTime['bank_transfer'] ?></td>
                <td class="numeric"><?= $refundAllTime['cheque'] ?></td>
                <td class="numeric"><?= $refundAllTime['total_refund_amount'] ?></td>
            </tr>
            </tbody>
        </table>

        <?php $refundByDay = $refund['byDay']; ?>

        <h3 class="heading-small">By Day - last <?= count($refundByDay) ?> SOP1 forms</h3>

        <table>
            <thead>
            <tr>
                <th class="numeric" style="width: 25%">Date</th>
                <th class="numeric" style="width: 25%">Number of refunds by bank transfer</th>
                <th class="numeric" style="width: 25%">Number of refunds by cheque</th>
                <th class="numeric" style="width: 25%">Total refund value</th>
            </tr>
            </thead>
            <tbody>
            <?php foreach ($refundByDay as $day => $counts){ ?>
                <tr>
                    <td class="numeric"><?= $day ?></td>
                    <td class="numeric"><?= $counts['bank_transfer'] ?></td>
                    <td class="numeric"><?= $counts['cheque'] ?></td>
                    <td class="numeric"><?= $counts['total_refund_amount'] ?></td>
                </tr>
            <?php } ?>
            </tbody>
        </table>

        <?php $refundByWeek = $refund['byWeek']; ?>

        <h3 class="heading-small">By week - last <?= count($claimByWeek) ?> weeks</h3>

        <table>
            <thead>
            <tr>
                <th class="numeric" style="width: 20%">Date</th>
                <th class="numeric" style="width: 20%">Number of spreadsheets</th>
                <th class="numeric" style="width: 20%">Number of refunds by bank transfer</th>
                <th class="numeric" style="width: 20%">Number of refunds by cheque</th>
                <th class="numeric" style="width: 20%">Total refund value</th>
            </tr>
            </thead>
            <tbody>
            <?php foreach ($refundByWeek as $week => $counts){ ?>
                <tr>
                    <td class="numeric"><?= $week ?></td>
                    <td class="numeric"><?= $counts['number_of_spreadsheets'] ?></td>
                    <td class="numeric"><?= $counts['bank_transfer'] ?></td>
                    <td class="numeric"><?= $counts['cheque'] ?></td>
                    <td class="numeric"><?= $counts['total_refund_amount'] ?></td>
                </tr>
            <?php } ?>
            </tbody>
        </table>

        <?php $refundByMonth = $refund['byMonth']; ?>

        <h3 class="heading-small">By month - last <?= count($refundByMonth) ?> months</h3>

        <table>
            <thead>
            <tr>
                <th class="numeric" style="width: 20%">Date</th>
                <th class="numeric" style="width: 20%">Number of spreadsheets</th>
                <th class="numeric" style="width: 20%">Number of refunds by bank transfer</th>
                <th class="numeric" style="width: 20%">Number of refunds by cheque</th>
                <th class="numeric" style="width: 20%">Total refund value</th>
            </tr>
            </thead>
            <tbody>
            <?php foreach ($refundByMonth as $month => $counts){ ?>
                <tr>
                    <td class="numeric"><?= $month ?></td>
                    <td class="numeric"><?= $counts['number_of_spreadsheets'] ?></td>
                    <td class="numeric"><?= $counts['bank_transfer'] ?></td>
                    <td class="numeric"><?= $counts['cheque'] ?></td>
                    <td class="numeric"><?= $counts['total_refund_amount'] ?></td>
                </tr>
            <?php } ?>
            </tbody>
        </table>

    </div>
</div>
