<h1>Sign in</h1>

<?php $this->insert('snippet::error-summary', ['form' => $form]) ?>

<form action="/sign-in" method="post" class="form">

    <?php $this->insert('snippet::form-csrf', ['form' => $form]) ?>

    <fieldset>

        <?php $this->insert('snippet::input-text', [
            'formElement' => $form->get('email'),
            'formLabel' => 'Email address',
            'formType' => 'text',
            'formLabelBold' => false
        ]) ?>

        <?php $this->insert('snippet::input-text', [
            'formElement' => $form->get('password'),
            'formLabel' => 'Password',
            'formType' => 'text',
            'formLabelBold' => false
        ]) ?>

    </fieldset>

    <div class="form-group">
        <input type="submit" class="button" value="Continue" />
    </div>

</form>
