<?php $this->layout('layout::default', ['title' => 'Sign in']) ?>

<div class="grid-row">
    <div class="column-full">

        <form method="post" class="form">

            <fieldset>

                <legend>
                    <h1 class="heading-xlarge">Sign in</h1>
                </legend>

                <?php $this->insert('snippet::error-summary', ['form' => $form]) ?>

                <?php $this->insert('snippet::input-hidden', ['formElement' => $form->get('secret')]) ?>

                <?php $this->insert('snippet::input-text', [
                    'formElement' => $form->get('email'),
                    'formLabel' => 'Email address',
                    'formType' => 'text',
                    'formLabelBold' => false
                ]) ?>

                <?php $this->insert('snippet::input-text', [
                    'formElement' => $form->get('password'),
                    'formLabel' => 'Password',
                    'formType' => 'password',
                    'formLabelBold' => false
                ]) ?>

            </fieldset>

            <div class="form-group">
                <input class="button" type="submit" value="Continue">
            </div>

            <a class="button button-link" href="<?= $this->generateUrl('password.request.reset') ?>">Forgotten your password?</a>

        </form>
    </div>
</div>
