<?php $this->layout('layout::default') ?>

<div class="grid-row">
    <div class="column-two-thirds">

        <h1 class="heading-xlarge">
            Check your refund claim
        </h1>

        <table class="check-your-answers form-group">
            <tbody>
                <tr>
                    <td>
                        Donor details
                    </td>
                    <td>
                        <p>Name: <?= $details['donor']['name']['title'] ?> <?= $details['donor']['name']['first'] ?> <?= $details['donor']['name']['last'] ?></p>
                        <p>DOB: <?= $details['donor']['dob'] ?></p>
                    </td>
                    <td class="change-answer">
                        <a href="<?= $this->url('apply.donor', ['who'=>$who]) ?>">
                            Change <span class="visuallyhidden">donor details</span>
                        </a>
                    </td>
                </tr>
                <?php if ($who === 'attorney'): ?>
                <tr>
                    <td>Attorney details</td>
                    <td>
                        <p>Name: <?= $details['attorney']['name']['title'] ?> <?= $details['attorney']['name']['first'] ?> <?= $details['attorney']['name']['last'] ?></p>
                        <p>DOB: <?= $details['attorney']['dob'] ?></p>
                    </td>
                    <td class="change-answer">
                        <a href="<?= $this->url('apply.attorney', ['who'=>$who]) ?>">
                            Change <span class="visuallyhidden">attorney details</span>
                        </a>
                    </td>
                </tr>
                <?php endif ?>
                <tr>
                    <td>Power of attorney details</td>
                    <td>
                        <p>Case number: <?= $details['verification']['case-number'] ?? '-Not supplied-' ?></p>
                        <p>Donor postcode: <?= $details['verification']['donor-postcode'] ?? '-Not supplied-' ?></p>
                        <p>Attorney name: <?= $details['verification']['attorney-name'] ?? '-Not supplied-' ?></p>
                        <p>Attorney postcode: <?= $details['verification']['attorney-postcode'] ?? '-Not supplied-' ?></p>
                    </td>
                    <td class="change-answer">
                        <a href="<?= $this->url('apply.verification', ['who'=>$who]) ?>">
                            Change <span class="visuallyhidden">power of attorney details</span>
                        </a>
                    </td>
                </tr>
                <tr>
                    <td>Contact details</td>
                    <td>
                        <?= (isset($details['contact']['email'])) ? "<p>Email: {$details['contact']['email']}</p>" : '' ?>
                        <?= (isset($details['contact']['mobile'])) ? "<p>Mobile: {$details['contact']['mobile']}</p>" : '' ?>
                    </td>
                    <td class="change-answer">
                        <a href="<?= $this->url('apply.contact', ['who'=>$who]) ?>">
                            Change <span class="visuallyhidden">contact details</span>
                        </a>
                    </td>
                </tr>
            </tbody>
        </table>

        <div class="form-group">
            <a class="button" href="<?= $this->url('apply.account', ['who'=>$who]) ?>">Continue</a>
        </div>
    </div>
</div>
