<?php
$title = 'Check your refund claim';
$this->layout('layout::default', [
    'title' => $title,
]);
?>

<h1 class="heading-xlarge">
    <?= $this->e($title) ?>
</h1>

<?php $this->insert('snippet::error-summary', [ 'form'=>$form ]) ?>

<dl class="govuk-check-your-answers cya-questions-short">
    
    <?php $this->insert('snippet::check-your-details-section', [
        'title' => 'Donor details',
        'fields' => [
            [ 'value' => "{$details['donor']['name']['title']} {$details['donor']['name']['first']} {$details['donor']['name']['last']}" ],
            [ 'value' => date('j F Y', strtotime($details['donor']['dob'])) ],
            [
                    'label' => (isset($details['donor']['poa-name']['first'])) ? 'Name on power of attorney' : null,
                    'value' => (isset($details['donor']['poa-name']['first'])) ? "{$details['donor']['poa-name']['title']} {$details['donor']['poa-name']['first']} {$details['donor']['poa-name']['last']}" : null
            ],

        ],
        'changeURL' => $this->url('apply.donor', ['who'=>$applicant])
    ]) ?>

    <?php $this->insert('snippet::check-your-details-section', [
        'title' => 'Attorney details',
        'fields' => [
            [ 'value' => "{$details['attorney']['name']['title']} {$details['attorney']['name']['first']} {$details['attorney']['name']['last']}" ],
            [ 'value' => date('j F Y', strtotime($details['attorney']['dob'])) ],
            [
                'label' => (isset($details['attorney']['poa-name']['first'])) ? 'Name on power of attorney' : null,
                'value' => (isset($details['attorney']['poa-name']['first'])) ? "{$details['attorney']['poa-name']['title']} {$details['attorney']['poa-name']['first']} {$details['attorney']['poa-name']['last']}" : null
            ],
        ],
        'changeURL' => $this->url('apply.attorney', ['who'=>$applicant])
    ]) ?>


    <?php $this->insert('snippet::check-your-details-section', [
        'title' => 'Power of attorney case number',
        'fields' => [
            [ 'value' => isset($details['case-number']['poa-case-number']) ?
                (strlen($details['case-number']['poa-case-number']) == 12)
                    ? rtrim(chunk_split($details['case-number']['poa-case-number'], 4, '-'), '-')
                    : $details['case-number']['poa-case-number']
                : 'Not entered' ]
        ],
        'changeURL' => $this->url('apply.case', ['who'=>$applicant])
    ]) ?>

    <?php if (!isset($details['case-number']['poa-case-number'])): ?>

        <?php $this->insert('snippet::check-your-details-section', [
            'title' => 'Power of attorney postcodes',
            'fields' => [
                [
                    'label' => 'Donor postcode',
                    'value' => ($details['postcodes']['donor-postcode']) ?? 'Not entered'
                ],
                [
                    'label' => 'Attorney postcode',
                    'value' => ($details['postcodes']['attorney-postcode']) ?? 'Not entered'
                ]
            ],
            'changeURL' => $this->url('apply.postcode', ['who'=>$applicant])
        ]) ?>

    <?php endif ?>

    <?php $this->insert('snippet::check-your-details-section', [
        'title' => 'Your contact details',
        'fields' => [
            [
                'label' => 'Email address',
                'value' => ($details['contact']['email']) ?? 'Not entered'
            ],
            [
                'label' => 'Phone number',
                'value' => ($details['contact']['phone']) ?? 'Not entered'
            ]
        ],
        'changeURL' => $this->url('apply.contact', ['who'=>$applicant])
    ]) ?>

    <?php $this->insert('snippet::check-your-details-section', [
        'title' => 'Donor bank details',
        'fields' => [
            [ 'value' => 'Bank details hidden for your security' ]
        ],
        'changeURL' => $this->url('apply.account', ['who'=>$applicant])
    ]) ?>

</dl>

<h2 class="heading-medium">Statement of truth</h2>

<p>By submitting this claim you confirm that, to the best of your knowledge:</p>

<ul class="list list-bullet">
    <li>you are entitled to claim a refund</li>
    <li>the details you have given are correct </li>
</ul>

<p class="text">
    You also accept that the details you've given will be used to process
    a refund, as explained in our <a href="#">terms and conditions</a>. 
</p>

<form class="form" action="<?= $form->getAttribute('action') ?? $this->url() ?>" method="<?= $this->e(strtolower($form->getAttribute('method'))) ?>">

    <?php $this->insert('snippet::form-csrf', [ 'form'=>$form ]) ?>

    <input type="submit" class="button" value="Confirm and submit claim">
    
</form>
        