<?php
$title = 'Terms and conditions';
$this->layout('layout::standard', [
    'title' => $title,
]);
?>

<p>People who made powers of attorney in England and Wales from April 2013 to March 2017 are entitled to a 
    partial refund of any application fees paid.</p>

<p>By applying for a refund using this online service you agree to these terms and conditions, and confirm that:</p>

<ul class="list list-bullet">
    <li>the information you've provided is correct, to the best of your knowledge</li>
    <li>you are the 'donor' (the person who made a power of attorney), or are claiming the 
        refund on their behalf and for them (as their attorney, for example)
    </li>
    <li>the bank details you've given are the donor's</li>
</ul>

<p>The refund is for the donor, even if someone else paid the fees at the time.</p>

<div class="notice">
    <p>
        <i class="icon icon-important">
            <span class="visually-hidden">Warning</span>
        </i>
        <strong class="bold-small">
        You could be breaking the law if you deliberately give untrue or misleading information.
        </strong>
    </p>
</div>

<h2 class="heading-large">When to apply another way</h2>

<p>You will need to call the Refunds Helpline instead of using this online service if:</p>

<ul class="list list-bullet">
    <li>the donor has a court-appointed deputy representing them</li>
    <li>the donor has died but you want to claim the refund for the estate</li>
    <li>you can't give the donor's bank account number and sort code</li>
</ul>

<h2 class="heading-large">Data and privacy</h2>

<p>When you make a claim online you will be asked for a range of information, including details 
    of the people named in the power of attorney. (You can give details from any of 
    the powers of attorney, if the donor made more than one.) You will also be asked 
    for a contact phone number or email address.
</p>

<p>We might also collect information if you contact the Refunds Helpline. For example,
    if you contact us to ask a question or to make a complaint.
</p>

<h3 class="heading-medium">Keeping your information safe</h3>

<p>Information you enter online will be temporarily and securely held in line with our
    <a href="/cookies">cookie policy</a> so that you can progress through your claim. 
    However, this information won't be stored unless, and until, you choose to submit your claim.</p>

<p>Once you submit a refund claim we will:</p>

<ul class="list list-bullet">
    <li>make sure your information is safe and that no unauthorised person has access to it</li>
    <li>make sure we do not keep your information any longer than we need to</li>
    <li>let you change your information if you tell us you made a mistake or that the details have changed</li>
</ul>

<h3 class="heading-medium" id="bank-details">Bank details</h3>

<p>The bank account number and sort code given must be those of the donor. If you can't
     provide the donor's details, contact the Refunds Helpline instead.
</p>

<p>The power of attorney refund service encrypts bank details. This means our staff can't see the 
    bank account number or sort code you give.</p>

<p>Encrypted bank details are then securely transferred to financial services provider Shared Services
    Connected Limited (SSCL). They only use these details to process refund payments in 
    line with the SSCL terms of service.</p>

<h3 class="heading-medium">If we need more information</h3>

<p>We might need to contact you for more information before we can confirm or pay a refund.
We will use the email address or phone number you give us. If we can't contact you or get 
no response your refund claim could be cancelled. 
</p>

<h3 class="heading-medium">If something changes</h3>

<p>Contact the Refunds Helpline to tell us if anything changes after you've made a refund claim.
    For example, if:</p>

<ul class="list list-bullet">
    <li>your contact details change</li>
    <li>the donor's bank details change</li>
</ul>

<p>You should also let us know if you think the information you gave was incorrect.</p>

<h3 class="heading-medium">Sharing information</h3>

<p>We will only share the information you give when the law says we can. This 
    includes sharing information to protect vulnerable people, in line with the Mental Capacity Act 2005.
</p>

<p>We will never share your information for marketing or commercial purposes.</p>

<div class="panel panel-border-wide">
    <p>Under the Data Protection Act, you can ask for a copy of the information we hold about you
        by making a 'subject access request' (SAR). Follow the process in the
        <a href="https://www.gov.uk/government/organisations/office-of-the-public-guardian/about/personal-information-charter#access-to-personal-information">
            Personal information charter</a>.
    </p>
</div>

<h2 class="heading-large">Refund amounts</h2>

<p>Refunds apply to:</p>

<ul class="list list-bullet">
    <li>lasting powers of attorney (LPAs) for financial affairs, and for health and welfare</li>
    <li>enduring powers of attorney (EPAs) - an earlier type of power of attorney</li>
</ul>

<?php $this->insert('snippet::refund-amounts');?>

<h2 class="heading-large">Rejections and appeals</h2>

<p>A refund can only be paid if any original fees were paid from April 2013 to March 2017, inclusive.</p>

<p>If your refund claim is rejected but you believe there has been a mistake you can call the Refunds
    Helpline to appeal the decision.
</p>

<h2 class="heading-large">Your feedback</h2>

<p>We welcome your views on this service and there is an
    optional survey to take after you've submitted a refund claim.
</p>

<p>We also collect anonymous site-usage information. This helps us to 
    see how the service is used and how we can make it better.
</p>

<h2 class="heading-large">Changes to these terms</h2>

<p>We may occasionally update these terms and conditions. This might happen
    if there's a change in the law or to the way the service works.
</p>

<h2 class="heading-large">If you suspect fraud or abuse</h2>

<p>
    Contact the Refunds Helpline if you believe someone has made a fraudulent claim. 
    If you suspect abuse, or that someone is in immediate danger, you should <a href="https://www.gov.uk/contact-police">contact the police</a>.
</p>

<?php $this->insert('snippet::refunds-helpline', [
    'headingLarge' => true
]) ?>
<?php $this->insert('snippet::refunds-postal-address');?>