<?php
$title = 'Terms and conditions';
$this->layout('layout::standard', [
    'title' => $title,
]);
?>

<p>By applying for a refund using this service you agree to these terms and conditions.</p>

<p>You confirm that:</p>

<ul class="list list-bullet">
    <li>the information you've provided is correct, to the best of your knowledge</li>
    <li>you are the 'donor' (the person who made a power of attorney), or are claiming the 
        refund on their behalf and for them (as their attorney, for example)
    </li>
    <li>the bank details you've given are the donor's</li>
</ul>

<div class="notice">
    <p>
        <i class="icon icon-important">
            <span class="visually-hidden">Warning</span>
        </i>
        <strong class="bold-small">
        You could be committing fraud if you deliberately give untrue or misleading information.
        </strong>
    </p>
</div>

<h2 class="heading-medium">When you can't use this service</h2>

<p>You will need to call the Refunds Helpline instead of using this service if:</p>

<ul class="list list-bullet">
    <li>the donor has a court-appointed deputy representing them</li>
    <li>the donor has died but you want to claim the refund - for the estate, for example</li>
</ul>

<h2 class="heading-large" id="bank-details">Bank details</h2>

<p>The bank details you provide must belong to the donor. If you can't provide the donor's details, contact the Refunds Helpline instead.</p>

<h3 class="heading-medium">Keeping bank details safe</h3>

<p>The power of attorney refund service encrypts bank details. This means our staff can't see the bank account number or sort code you give.</p>

<p>Encrypted bank details are then securely transferred to financial services provider Shared Services 
    Connected Limited (SSCL). They use these details to process a refund payments
     in line with the SSCL terms of service.</p>

<h2 class="heading-large">Other information we ask for</h2>

<p>You'll be asked for a range of information, including details of the people named in the power 
    of attorney. (You can give details from any of the powers of attorney, if the donor made
     more than one.) You'll also be asked for a contact phone number or email address. 
    We might also collect information if you contact the Refunds Helpline. For example, 
    if you contact us to ask a question or to make a complaint.
</p>

<h3 class="heading-medium">Keeping information safe</h3>

<p>Information you enter online will be temporarily and securely held in line with our 
    <a href="/cookies">cookie policy</a> so that you can progress through your claim. However, this 
    information won't be permanently stored unless, and until, you choose to submit your claim.</p>

<p>Once you submit a refund claim we will:</p>

<ul class="list list-bullet">
    <li>make sure your information is safe and that no unauthorised person has access to it</li>
    <li>make sure we do not keep your information any longer than we have to</li>
    <li>give you the chance to ask us to change your information if you believe it is wrong</li>
</ul>

<h3 class="heading-medium">If we need more information</h3>

<p>We might need to contact you for more information before we can confirm or pay a refund. We 
    will use the email address or phone number you give us. If we can't contact you 
    or get no response your refund claim could be cancelled. 
</p>

<h3 class="heading-medium">If something changes</h3>

<p>Contact the Refunds Helpline to tell us if the following change after you've made a refund claim:</p>

<ul class="list list-bullet">
    <li>your contact details</li>
    <li>the donor's bank details</li>
</ul>

<p>You should also let us know if you think the information you gave was incorrect.</p>

<h3 class="heading-medium">Sharing information</h3>

<p>We will only share the information you give when the law says we can. This includes sharing
    information to protect vulnerable people, in line with the Mental Capacity Act 2005.
</p>

<p>We may share your contact information with organisations carrying out research on our behalf. 
    They must make sure that any information we give them is kept safe and not use it
    for any other purpose.</p>

<p>We'll never share your information for marketing or commercial purposes.</p>

<p>Under the Data Protection Act, you can ask for a copy of the information we hold about you
    by making a 'subject access request' (SAR). Follow the process in the Personal information charter.
</p>

<h2 class="heading-large">Rejections and appeals</h2>

<p>A refund can only be paid if any original fees were paid from April 2013 to March 2017, inclusive.</p>

<p>If your refund claim is rejected but you believe there has been a mistake you can call
    the Refunds Helpline to appeal the decision.
</p>

<h2 class="heading-large">Your feedback</h2>

<p>We welcome your views on this service. We invite feedback through links in the service,
    and there's an optional survey to take after you've submitted a refund claim.
</p>

<p>We also collect anonymous site-usage information. This helps us to see how the
    service is used and how we can make it better.
</p>

<h2 class="heading-large">Availability of this service</h2>

<p>While we make every effort to ensure this service is accessible at all times, we are not
    liable if the service is unavailable for any period.
</p>

<h2 class="heading-large">Changes to these terms</h2>

<p>We may occasionally update these terms and conditions.
    This might happen if there's a change in the law or to the way the service works.
</p>

<?php $this->insert('snippet::refunds-helpline');?>