<?php
$title = 'Test page';
$this->layout('layout::default', [
    'title' => $title,
]);
?>

<?php $this->start('intro-text') ?>
  <p>A refund can be claimed by a donor or by an attorney.</p>

  <p>
    If you're an attorney, you can claim for all of the LPA applications, not just those
    where you've been appointed attorney.
  </p>
<?php $this->stop() ?>

<?php $this->start('help-text') ?>
  <details>
    <summary><span class="summary">Help with this question</span></summary>
    <div class="panel panel-border-narrow">
      <p>
        Donor is the person appointing other people to make decisions on their behalf.
      </p>

      <p>
        Attorneys are the people the donor picks to make decisions for them.
      </p>

      <p>Deputy is assigned if donor has lost mental capacity and attorney has lost mental
        capacity or died.
      </p>
    </div>
  </details>
<?php $this->stop() ?>



<div class="multiple-choice">
  <input id="radio-1" type="radio" name="applicant" value="donor">
  <label for="radio-1">Donor</label>
</div>
<div class="multiple-choice">
  <input id="radio-2" type="radio" name="applicant" value="attorney">
  <label for="radio-2">Attorney</label>
</div>
<p class="form-block">or</p>
<div class="multiple-choice">
  <input id="radio-3" type="radio" name="applicant" value="deputy">
  <label for="radio-3">Deputy</label>
</div>