<?php $this->layout('layout::default', ['title' => 'Home']) ?>

<?php $this->insert('snippet::error-summary', ['form' => $form]) ?>

<div class="grid-row">
    <div class="column-full">

        <h2 class="heading-medium heading-refunds"><?= (isset($user) ? 'Edit user' : 'Add user') ?></h2>

        <form method="post" class="form">

            <?php $this->insert('snippet::form-csrf', ['form' => $form]) ?>

            <fieldset>

                <?php $this->insert('snippet::input-text', [
                    'formElement' => $form->get('name'),
                    'formLabel' => 'Name',
                    'formType' => 'text',
                    'formLabelBold' => false
                ]) ?>

                <?php $this->insert('snippet::input-text', [
                    'formElement' => $form->get('email'),
                    'formLabel' => 'Email',
                    'formType' => 'text',
                    'formLabelBold' => false
                ]) ?>

            </fieldset>

            <p>
                <input type="submit" class="button" value="Save" />
                <a class="button button-secondary" href="<?= $this->generateUrl('user', ['id' => (isset($user) ? $user->getId() : null) ]) ?>">Cancel</a>
            </p>

        </form>
    </div>
</div>
