<?php $this->layout('layout::default', ['title' => 'Home']) ?>

<table>
    <tr>
        <th>Name</th>
        <td><?= $user->getName() ?></td>
    </tr>
    <tr>
        <th>Email</th>
        <td><?= $user->getEmail() ?></td>
    </tr>
    <tr>
        <th>Status</th>
        <td><?= $user->getStatus() ?></td>
    </tr>
    <tr>
        <th>Roles</th>
        <td><?= $user->getRoles() ?></td>
    </tr>
</table>

<p><a href="<?= $this->generateUrl('user.edit', ['id' => $user->getId()]) ?>">Edit</a></p>
<p><a href="<?= $this->generateUrl('user', ['id' => null]) ?>">Back to users</a></p>
