<?php $this->layout('layout::default', ['title' => 'Home']) ?>

<?php $this->insert('snippet::error-summary', ['form' => $form]) ?>

<div class="grid-row">
    <div class="column-full">

        <h2 class="heading-medium heading-refunds"><?= (isset($user) ? 'Edit user' : 'Add user') ?></h2>

        <form method="post" class="form">

            <?php $this->insert('snippet::form-csrf', ['form' => $form]) ?>

            <fieldset>

                <?php $this->insert('snippet::input-text', [
                    'formElement' => $form->get('name'),
                    'formLabel' => 'Name',
                    'formType' => 'text',
                    'formLabelBold' => false
                ]) ?>

                <?php $this->insert('snippet::input-text', [
                    'formElement' => $form->get('email'),
                    'formLabel' => 'Email',
                    'formType' => 'text',
                    'formLabelBold' => false
                ]) ?>

                <?php $this->insert('snippet::input-radio', [
                    'formElement' => $form->get('roles'),
                    'question' => 'Roles',
                    'options' => [
                        \Opg\Refunds\Caseworker\DataModel\Cases\User::ROLE_CASEWORKER => [
                            'optionLabel' => 'Caseworker'
                        ],
                        \Opg\Refunds\Caseworker\DataModel\Cases\User::ROLE_REFUND => [
                            'optionLabel' => 'Refund Manager'
                        ],
                        \Opg\Refunds\Caseworker\DataModel\Cases\User::ROLE_REPORTING => [
                            'optionLabel' => 'Reporting Manager'
                        ],
                        \Opg\Refunds\Caseworker\DataModel\Cases\User::ROLE_ADMIN => [
                            'optionLabel' => 'Service Management Team'
                        ],
                    ],
                ])
                ?>

                <?php $this->insert('snippet::input-radio', [
                    'formElement' => $form->get('status'),
                    'question' => 'Status',
                    'options' => [
                        \Opg\Refunds\Caseworker\DataModel\Cases\User::STATUS_ACTIVE => [
                            'optionLabel' => 'Active'
                        ],
                        \Opg\Refunds\Caseworker\DataModel\Cases\User::STATUS_INACTIVE => [
                            'optionLabel' => 'Inactive'
                        ],
                    ],
                ])
                ?>

            </fieldset>

            <p>
                <input type="submit" class="button" value="Save" />
                <a class="button button-secondary" href="<?= $this->generateUrl('user', ['id' => (isset($user) ? $user->getId() : null) ]) ?>">Cancel</a>
            </p>

        </form>
    </div>
</div>
