<?php $this->layout('layout::default', ['title' => 'Users']) ?>

<h2 class="heading-medium">Delete user</h2>

<form method="post" class="form">

    <?php $this->insert('snippet::input-hidden', ['formElement' => $form->get('secret')]) ?>

    <?php if ($deletingSelf) { ?>
        <p>You are about to delete your own account. Are you sure you want to continue?</p>
    <?php }else { ?>
        <p>Are you sure you want to delete <?= $this->e($user->getName()) ?>?</p>
    <?php } ?>

    <div class="form-group">
        <input type="submit" class="button" style="background-color: red;" name="submit" value="Delete">
        <a class="button button-link" href="<?= $this->generateUrl('user', ['id' => $user->getId()]) ?>">Cancel</a>
    </div>

</form>