<?php $this->layout('layout::default', ['title' => 'Home']) ?>

<div class="grid-row">
    <div class="column-full">

        <?php // $this->insert('snippet::flash-messages', ['messages' => $messages]) ?>

        <h2 class="heading-medium heading-refunds">Users (<?= count($users) ?>)</h2>

        <table>
            <thead>
                <tr>
                    <th>Name</th>
                    <th>Email</th>
                    <th>Status</th>
                    <th>Roles</th>
                </tr>
            </thead>
            <tbody>
            <?php if (count($users)) { ?>
                <?php foreach ($users as $user) { ?>
                    <tr>
                        <td>
                            <a href="<?= $this->generateUrl('user', ['id' => $user->getId()]) ?>"><?= $user->getName() ?></a>
                            <?php if ($user->getStatus() === \Opg\Refunds\Caseworker\DataModel\Cases\User::STATUS_INACTIVE) { ?>
                                - <span style="color: red;">INACTIVE</span>
                            <?php } ?>
                        </td>
                        <td><?= $user->getEmail() ?></td>
                        <td><?= $user->getStatus() ?></td>
                        <td><?= implode(', ', $user->getRoles()) ?></td>
                    </tr>
                <?php } ?>
            <?php } else { ?>
                <tr>
                    <td colspan="4">No users</td>
                </tr>
            <?php } ?>
            </tbody>
        </table>
    </div>
</div>

<div class="grid-row">
    <div class="column-full">
        <p><a class="button" href="<?= $this->generateUrl('user.add') ?>">Add user</a></p>
    </div>
</div>
