<?php
$title = 'Verification details';
$this->layout('layout::standard', [
    'title' => $title,
]);
?>

<?php $this->insert('snippet::error-summary', [ 'form'=>$form ]) ?>

<form class="form" action="<?= $form->getAttribute('action') ?? $this->url() ?>" method="<?= $this->e(strtolower($form->getAttribute('method'))) ?>">

    <?php $this->insert('snippet::form-csrf', [ 'form'=>$form ]) ?>

    <div class="form-group">
        <fieldset>
            <legend class="visually-hidden">Case number</legend>

            <?php $this->insert('snippet::input-text', [
                'formElement' => $form->get('case-number'),
                'formLabel' => 'Case number',
                'formType' => 'text',
                'formLabelBold' => false
            ]) ?>

        </fieldset>
    </div>

    <div class="form-group">
        <fieldset>
            <legend class="visually-hidden">Donor postcode</legend>

            <?php $this->insert('snippet::input-text', [
                'formElement' => $form->get('donor-postcode'),
                'formLabel' => 'Donor postcode',
                'formType' => 'text',
                'formLabelBold' => false
            ]) ?>

        </fieldset>
    </div>

    <div class="form-group">
        <fieldset>
            <legend class="visually-hidden">Attorney name</legend>

            <?php $this->insert('snippet::input-text', [
                'formElement' => $form->get('attorney-name'),
                'formLabel' => 'Attorney name',
                'formType' => 'text',
                'formLabelBold' => false
            ]) ?>

        </fieldset>
    </div>

    <div class="form-group">
        <fieldset>
            <legend class="visually-hidden">Attorney postcode</legend>

            <?php $this->insert('snippet::input-text', [
                'formElement' => $form->get('attorney-postcode'),
                'formLabel' => 'Attorney postcode',
                'formType' => 'text',
                'formLabelBold' => false
            ]) ?>

        </fieldset>
    </div>

    <div class="form-group">
        <input class="button" type="submit" value="Continue">
    </div>

</form>


