<?php
$title = 'About you';
$this->layout('layout::standard', [
        'title' => $title,
        'form' => $form
    ]);

$form->setAttribute('method', 'get');
$form->setAttribute('action', $this->url('eligibility.who.answer'));
?>

<?php $this->insert('snippet::error-summary', [ 'form'=>$form ]) ?>

<p>A refund can only be claimed by the donor or by one of their attorneys.</p>

<form class="form" action="<?= $form->getAttribute('action') ?? $this->url() ?>" method="<?= $this->e(strtolower($form->getAttribute('method'))) ?>">

    <?php $this->insert('snippet::input-radio', [
        'formElement' => $form->get('who'),
        'question' => $title,
        'options' => [
            'donor' => [
                'optionLabel' => "I am the 'donor'",
            ],
            'attorney' => [
                'optionLabel' => "I am an 'attorney'",
            ]
        ],
    ])
    ?>

    <div class="panel panel-border-narrow js-hidden" id="attorney-info">
        <p>You should check that any other attorneys haven’t already claimed the refund.</p>
    </div>

    <div class="form-group">
        <input class="button" type="submit" value="Continue">
    </div>

</form>


